### ISSUE TITLE
Shared memory tensors may need to be declared outside of unswitched IfThenElse blocks

### ISSUE THREAD

**Issue by naoyam** [csarofeen/pytorch#1133]
When unswitch conditions are threadIdx-dependent, the path taken by each thread, either the unswitched or normal path, may not be uniform within a thread block. And if a shared memory tensor is defined inside the unswitched block, since it is replicated, the tensor is not really shared between all threads in a thread block.

E.g.:
```
  if ((((((((((((ceilDiv(T0.size[0], 4)) - 1) * 4) + ((nvfuser_index_t)threadIdx.y)) < T0.size[0]) && (((nvfuser_index_t)threadIdx.y) < 4)) && (((((ceilDiv(T0.size[0], 4)) - 1) * 4) + ((nvfuser_index_t)threadIdx.z)) < T0.size[0])) && (((nvfuser_index_t)threadIdx.z) < 4)) && (((((ceilDiv(T0.size[0], 4)) - 1) * 4) + ((nvfuser_index_t)threadIdx.x)) < T0.size[0])) && (((nvfuser_index_t)threadIdx.x) < 4)) && (((((nvfuser_index_t)threadIdx.x) == 0) && (((nvfuser_index_t)threadIdx.y) == 0)) && (((nvfuser_index_t)threadIdx.z) == 0)))) {
    #pragma unroll 1
    for(nvfuser_index_t ki130 = 0; ki130 < (ceilDiv(T0.size[0], 4)); ++ki130) {
      __shared__ float T2[4];
      T2[((nvfuser_index_t)threadIdx.y)]
        = T0[(((ki130 * 4) + ((nvfuser_index_t)threadIdx.y)) * T0.stride[0])]
        + (float) 1;
      __barrier_sync(0);
      // Alias Allocation - shared
      float* T3 = T2;
      T3[((nvfuser_index_t)threadIdx.z)]
        = T2[((nvfuser_index_t)threadIdx.z)]
        + (float) 1;
    }
  } else {
    #pragma unroll 1
    for(nvfuser_index_t ki130 = 0; ki130 < (ceilDiv(T0.size[0], 4)); ++ki130) {
      __shared__ float T2[4];
      if ((((((ki130 * 4) + ((nvfuser_index_t)threadIdx.y)) < T0.size[0]) && (((nvfuser_index_t)threadIdx.y) < 4)) && ((((nvfuser_index_t)threadIdx.x) == 0) && (((nvfuser_index_t)threadIdx.z) == 0)))) {
        T2[((nvfuser_index_t)threadIdx.y)]
          = T0[(((ki130 * 4) + ((nvfuser_index_t)threadIdx.y)) * T0.stride[0])]
          + (float) 1;
      }
      __barrier_sync(0);
      // Alias Allocation - shared
      float* T3 = T2;
      if ((((((ki130 * 4) + ((nvfuser_index_t)threadIdx.z)) < T0.size[0]) && (((nvfuser_index_t)threadIdx.z) < 4)) && ((((nvfuser_index_t)threadIdx.x) == 0) && (((nvfuser_index_t)threadIdx.y) == 0)))) {
        T3[((nvfuser_index_t)threadIdx.z)]
          = T2[((nvfuser_index_t)threadIdx.z)]
          + (float) 1;
      }
```

In this case, `T2` is replicated. The root thread (i.e., `threadIdx.x == 0 && threadIdx.y == 0 && threadIdx.z == 0`) may take the unswitched path, and the rest definitely take the normal path, so they may see two different `T2` buffers.

I think the fix should define shared memory tensors outside unswitched conditional blocks. This would also avoid the problem of duplicated allocations.

**Comment by csarofeen** [comment]
Is this still an issue with:
https://github.com/csarofeen/pytorch/pull/1174
where the unswitch predicate won't have:
```
(((((nvfuser_index_t)threadIdx.x) == 0) && (((nvfuser_index_t)threadIdx.y) == 0)) && (((nvfuser_index_t)threadIdx.z) == 0))))
```
?

**Comment by naoyam** [comment]
> Is this still an issue with: #1174 where the unswitch predicate won't have:
> 
> ```
> (((((nvfuser_index_t)threadIdx.x) == 0) && (((nvfuser_index_t)threadIdx.y) == 0)) && (((nvfuser_index_t)threadIdx.z) == 0))))
> ```
> 
> ?

I think so. As long as `threadIdx` is used in unswitch predicates, there can be divergence of threads between the unswitched and normal paths, and then a shared memory tensor can not be accessible from threads taking a different path.
