### ISSUE TITLE
Adding a Reduction Heuristic Scheduler to match the Pytorch ATen TensorIterator

### ISSUE THREAD

**Issue by kevinstephano** [csarofeen/pytorch#116]
## 🚀 Feature

The goal is to make a "magic scheduler" that takes an algorithm with a reduction op and applies a TensorExpression schedule to match the performance of Pytorch's ATen TensorIterator.

My plan and heuristic are shown in this (NVIDIA Internal) document: https://docs.google.com/document/d/15b8JSnLYu9PIGwEltPXeKOoX5XR_EE_RMjPkRtQ8EHo/

Work is happening on this branch:
https://github.com/csarofeen/pytorch/tree/20_6_11_devel_redsched

Evaluation is happening with this code base:
https://github.com/kevinstephano/codegen_perf

### Part1: Basic Assumptions 2D, only scheduling just a reduction

- [x]  Get simple schedule up and running in a test
- [x] Reverse engineer the ATEN heuristic
- [x] Implement Aten's schedule
  - [x] Get a scheduler file and function stubbed out
  - [x] Add code to calculate BIDx, BIDy, TIDx, and TIDy splits
  - [x] Fix scheduling that needs to split based on remaining size
  - [x] Modify my codegen_perf code to compare against ATen
  - [x] Fix errors in going over fastest dimension reduction differences
  - [x] Add cross-block reductions
  - [x] Fix reductions not on fastest dimension.
  - [x] Need to fix outer dimension reductions with Vectorize.  The perf is off.
  - [x] Need to add FP16 support.  I am going to write out a test first to capture the behavior. 
- [ ] Perf test schedule

### Part2: Start Addressing assumptions

- [x] Generalize to more than 2D tensors
- [ ] Make schedule usable in the presence of other fusion ops. Should the scheduling be from the bottom up?

**Comment by kevinstephano** [comment]
Found a mismatch:

```
>>>CdGen Size: Grid:    1    1 Block:   32    8 Axis: 1 Dim0: 8 Dim1: 40 Total Bytes: 0.001 MB Elements: 328 Time: 2.119 us 0.1 %EFF      
>>>TIter Size: Grid:    1    1 Block:   32    8 Axis: 1 Dim0: 8 Dim1: 40 Total Bytes: 0.001 MB Elements: 328 Time: 2.638 us 0.1 %EFF      
>>>CdGen Size: Grid:    1    1 Block:   32    8 Axis: 1 Dim0: 8 Dim1: 72 Total Bytes: 0.002 MB Elements: 584 Time: 2.259 us 0.1 %EFF      
>>>TIter Size: Grid:    1    1 Block:   64    8 Axis: 1 Dim0: 8 Dim1: 72 Total Bytes: 0.002 MB Elements: 584 Time: 2.813 us 0.1 %EFF 
```

**Comment by kevinstephano** [comment]
The non-fastest dimension reductions have a couple issues:

1. Cross-block reductions are not incorporated
2. There is a significant perf difference. I am not confident it is purely just the lack of cross-block reductions.

```
>>>CdGen Size: Grid:   32    1 Block:   32    4 Axis: 0 Dim0: 1024 Dim1: 4096 Total Bytes: 16.794 MB Elements: 4198400 Time: 375.073 us 5.5 %EFF
>>>TIter Size: Grid:   32   16 Block:   32    4 Axis: 0 Dim0: 1024 Dim1: 4096 Total Bytes: 16.794 MB Elements: 4198400 Time: 32.607 us 63.2 %EFF
```

I am in the process of tedious code tracing as the non-fastest path calculations are not as explicit and rely on struct method side effects.  The non-fastest dimension reductions also noticeably incorporate load vectorization into their blocking.  I did this as well in a hacked way.

**Comment by kevinstephano** [comment]
This kernel has a data mismatch:

```
__global__ void CUDAGeneratedKernel(Tensor<float, 2> T0, Tensor<float, 1> T1, void* work_buf, unsigned* sync_flags){
  __shared__ float shared_mem[1024];
  if ( ( ( ( blockIdx.x * 32 ) + threadIdx.x ) < T1.size[0] ) ) {
    T1[ ( ( ( blockIdx.x * 32 ) + threadIdx.x ) * T1.stride[0] ) ]
       = float(0);    
  }                  
  float T2[1];  
  if ( ( ( ( ( ( ( 0 * 4 ) + threadIdx.y ) * 128 ) + blockIdx.y ) < T0.size[0] ) && ( ( ( blockIdx.x * 32 ) + threadIdx.x ) < T1.size[0] ) ) ) {
    T2[ 0 ] 
       = float(0);    
  }                  
  for(size_t i35 = 0; i35 < ( ceilDiv(( ceilDiv(T0.size[0], 128) ), 4) ); ++i35 ) {
    if ( ( ( ( ( ( ( i35 * 4 ) + threadIdx.y ) * 128 ) + blockIdx.y ) < T0.size[0] ) && ( ( ( blockIdx.x * 32 ) + threadIdx.x ) < T1.size[0] ) ) ) {
      T2[ 0 ]
         = T2[ 0 ]    
         + T0[ ( ( ( ( ( i35 * 4 ) + threadIdx.y ) * 128 ) + blockIdx.y ) * T0.stride[0] ) + ( ( ( blockIdx.x * 32 ) + threadIdx.x ) * T0.stride[1] ) ];
    }           
  }         
  if ( ( ( ( blockIdx.x * 32 ) + threadIdx.x ) < T1.size[0] ) ) {
    float block_result;
    blockReduce< false, true, false > ( block_result, T2[ 0 ], reduction_add_float, threadIdx, blockDim, reinterpret_cast<float*>(shared_mem));
    reduction::gridReduce< false, true, false, true, false, true > ( T1[ ( ( ( blockIdx.x * 32 ) + threadIdx.x ) * T1.stride[0] ) ], block_result, reduction_add_float, static_cast<float*>(work_buf), sync_flags, reinterpret_cast<float*>(shared_mem));
  }         
}           
```

Dim0: 8192 Dim1: 1024 Reduce on Dim: 0

**Comment by kevinstephano** [comment]
grid:8 128 block: 32 4

```
      red_tv->split(-1, block_dim_x);
      if(grid_dim_y > 1)
        red_tv->split(0,grid_dim_y);
      red_tv->split(0, block_dim_y);
      auto red_tv_rf = red_tv->rFactor({0});
      red_tv_rf->axis(-1)->parallelize(ParallelType::TIDx);
      red_tv_rf->axis(-2)->parallelize(ParallelType::BIDx);
      if(grid_dim_y > 1) {
        red_tv_rf->axis(-3)->parallelize(ParallelType::BIDy);
        red_tv_rf->axis(-4)->parallelize(ParallelType::TIDy);
      } else {
        red_tv_rf->axis(-3)->parallelize(ParallelType::TIDy);
      }
      red_tv->axis(-1)->parallelize(ParallelType::TIDx);
      red_tv->axis(-2)->parallelize(ParallelType::BIDx);
      red_tv->axis(-3)->parallelize(ParallelType::TIDy);
      if(grid_dim_y > 1) {
        red_tv->axis(-3)->parallelize(ParallelType::BIDy);
        red_tv->axis(-4)->parallelize(ParallelType::TIDy);
      } else {
        red_tv->axis(-3)->parallelize(ParallelType::TIDy);
      }
```

```
void reduction(int trials, int red_dim, int dim0, int dim1, bool ti_only) {
  torch::jit::fuser::cuda::CudaKernel prog;
  Fusion& fusion = *prog.fusion_;
  FusionGuard fg(&fusion);

  // Set up your input tensor views
  TensorView* tv0 = makeDummyTensor(2);
  fusion.addInput(tv0);

  TensorView* tv1 = reductionOp(BinaryOpType::Add, {red_dim}, new Float(0), tv0);
  fusion.addOutput(tv1);

  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  at::Tensor input = at::rand({dim0, dim1}, options);
  at::Tensor cg_output = at::empty({(red_dim == 0 ? dim1 : dim0) }, options);

  // Apply reduction heuristic
  const at::ArrayRef<c10::IValue> inputs({input});

  c10::optional<std::tuple<int,int,int,int>> blocking =
        Scheduler::reduction(prog.fusion_.get(), inputs);
  TORCH_CHECK(blocking != c10::nullopt, "Reduction is not found!");

  fusion.printMath();
  GPULower gpulw(&fusion);
  gpulw.printKernel(std::cout);

  prog.device_ = 0;
  prog.grid(std::get<0>(blocking.value()), std::get<1>(blocking.value()));
  prog.block(std::get<2>(blocking.value()), std::get<3>(blocking.value()));

  torch::jit::fuser::cuda::compileKernel(&prog);

  at::Tensor aten_output;
  for (int i = 0; i < trials; ++i) {
    if( !ti_only ) {
      at::Tensor flush_cache_1 = at::ones({6000*1024}, options);
      torch::jit::fuser::cuda::runTestKernel(&prog, {input}, {cg_output});
    }
    at::Tensor flush_cache_2 = at::ones({6000*1024}, options);
    aten_output = input.sum({red_dim});
  }
}
```

**Comment by kevinstephano** [comment]
Added a fix that enables the non-fast dim reduction to work. Thanks to Naoya's debug!  I think I am almost ready to merge.  Jie has a PR that puts in a different scheduler file format.  Therefore, it be good for his to PR to land before I try to change my stuff to his way.

**Comment by kevinstephano** [comment]
A first PR was merged: https://github.com/csarofeen/pytorch/pull/152

**Comment by kevinstephano** [comment]
From a discussion today Christian would like the Heuristic to be symbolically calculating the heuristic and returning a set of attributes that can be cached to indicate whether we have already generated a suitable kernel.  Second, another set of parameters should be returned for the known needed blocking parameters.  So far, those are gridDim.y, blockDim.x, and blockDim.y.  gridDim.x can be separately symbolically calculated.

**Comment by kevinstephano** [comment]
There are two outstanding issues:
1.) Grid Reductions don't work with an operation after them like a Cast Op for Fp16 support
2.) With loop unrolling, Cast Ops don't work because the Cast Op is addressing a 1-Element Tensor with an Loop-Index variable.  That is bad!

The second issue is also found here: https://github.com/csarofeen/pytorch/issues/176

**Comment by csarofeen** [comment]
This is done and works, closing.
