### ISSUE TITLE
[Bfloat16] Python Autodiff Test Failures

### ISSUE THREAD

**Issue by rdspring1** [csarofeen/pytorch#1185]
## 🐛 Bug

Found some bfloat16 test failures in `test/test_jit_cuda_fuser.py `

1. test_autocast_1_bfloat
2. test_autocast_2_bfloat 

```
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rspring/anaconda3/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1397, in wrapper
    method(*args, **kwargs)
  File "test/test_jit_cuda_fuser.py", line 2273, in test_autocast_1_bfloat
    jit_o.backward(grad)
  File "/home/rspring/anaconda3/lib/python3.8/site-packages/torch/_tensor.py", line 320, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/rspring/anaconda3/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "<string>", line 82, in <backward op>
            result = torch.softmax(self, dim, dtype)
            def backward(grad_output):
                grad_self = torch._softmax_backward_data(grad_output, result, dim, self.dtype)
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
                return grad_self, None, None
RuntimeError: expected input and grad types to match, or input to be at::Half and grad to be at::Float
```

**Comment by jjsjann123** [comment]
This is an issue with autodiff, not our fuser :sob:

implicit type promotion done by autograd is not visible by autodiff. We have to deal with similar issues in autocast.
If you look at the special case here:
> RuntimeError: expected input and grad types to match, or input to be at::Half and grad to be at::Float

I suspect we would want similar special case for at::bFloat input and at::Float grad added in aten ops.

**Comment by jjsjann123** [comment]
#957 <- reference in autocast

**Comment by jjsjann123** [comment]
Have we tried those test cases without nvfuser?

**Comment by rdspring1** [comment]
I can try `test_autocast_1_bfloat` and `test_autocast_2_bfloat` without nvfuser.

The other set of tests seem to be an internal error. Should I create a separate issue for them?

**Comment by jjsjann123** [comment]
it's fine to continue the discussion for the other failures in this threads.

**Comment by rdspring1** [comment]
#1201 < Separate `__bfloat2float` function error
