### ISSUE TITLE
Type Promotion and Special Number Handling

### ISSUE THREAD

**Issue by rdspring1** [csarofeen/pytorch#1187]
## 🐛 Bug
List of operations that have type promotion or special number errors:

### Unary
- [x] log
- [x] log10
- [x] log1p
- [x] log2
- [x] lgamma
- [x] exp
- [x] expm1
- [x] erf
- [x] erfc
- [x] cos
- [x] acos
- [x] cosh
- [x] sin
- [x] asin
- [x] tan
- [x] atan
- [x] sqrt
- [x] rsqrt
- [x] ceil
- [x] floor
- [x] round
- [x] trunc
- [x] frac
- [x] reciprocal
- [x] relu
- [x] sigmoid
- [x] tanh

### Binary
- [x] div
- [x] atan2
- [x] max
- [x] min
- [x] pow
- [x] remainder
- [x] fmod

### Ternary
- [x] where
- [ ] clamp
- [x] threshold

* Ternary Ops could also be missing all Tensor argument support

**Comment by jjsjann123** [comment]
linking relevant issues: #1185 #1167

**Comment by rdspring1** [comment]
link to arithmetic type promotion rules:
https://github.com/pytorch/pytorch/blob/master/docs/source/tensor_attributes.rst#type-promotion-doc
