### ISSUE TITLE
Enabling Autocast Support in LTC

### ISSUE THREAD

**Issue by kevinstephano** [csarofeen/pytorch#1313]
## 🚀 Feature
This is debatably a LTC request as Jie is also working on this problem.

An issue with autocast support is communicating to operator dispatch how to support autocast given that knowing you are on a `lazy` device is insufficient information.  You also need to know the type of device meaning whether you are on a `cpu` device or a `cuda` device.

Jie's initial workaround is to consult the env variable `LTC_TS_CUDA` when on a `lazy` device to infer whether you are on the cpu or gpu.

**Comment by jjsjann123** [comment]
We have this PR merged https://github.com/pytorch/pytorch/pull/69090

It's sorta working as we now have CUDA autocast dispatched on lazy device. It's definitely *NOT* a final~ish solution but it should do. We can revisit this topic when we have lazy mode.
