### ISSUE TITLE
Compilation time increase exponentially with a large number of pointwise ops

### ISSUE THREAD

**Issue by kevinstephano** [csarofeen/pytorch#1318]
## 🐛 Bug

This is definitely a somewhat pathological example, but compilation time seems to grow exponentially with this function
```
def f(x):
  for _ in range(15):
    x = x*x
  return x
inp = torch.randn(2**25, device='cuda')
f = torch.jit.script(f)
begin = time.time()
with torch.jit.fuser('fuser2'):
  for _ in range(5):
    f(inp)
print(time.time()-begin)
```

The time taken balloons to 16 seconds by the time we have 15 of them.
```
10 0.5022225379943848
11 0.9363245964050293
12 1.8568496704101562
13 3.834651231765747
14 8.179020404815674
15 17.446423292160034
```

From taking a look at some perf profiles, the primary culprit seems to be the schedulePointwise function: https://github.com/csarofeen/pytorch/blob/devel/torch/csrc/jit/codegen/cuda/scheduler/pointwise.cpp#L496
And more specifically, I suspect it's this function that's exponential in this case: https://github.com/csarofeen/pytorch/blob/devel/torch/csrc/jit/codegen/cuda/scheduler/utils.cpp#L569

**Comment by bitfort** [comment]
Adding to the datapoints:

for adding tensors together.

Size | Time (s)
-- | --
0 | 0.0003423690796
1 | 0.0003907680511
2 | 0.2659058571
3 | 0.2410721779
4 | 0.2432453632
5 | 0.2426133156
6 | 0.2436690331
7 | 0.2462940216
8 | 0.2510836124
9 | 0.2612607479
10 | 0.2804636955
11 | 0.3159413338
12 | 0.4044320583
13 | 0.5557813644
14 | 0.8420534134
15 | 1.451235533
16 | 2.837475777
17 | 6.000268936
18 | 12.5479362
19 | 27.31082129
20 | 54.03561544
21 | 119.6012893

**Comment by csarofeen** [comment]
@zasdfgbnm this is the original bug that we should validate for https://github.com/csarofeen/pytorch/pull/1743

**Comment by zasdfgbnm** [comment]
This is fixed. Not it takes <1s on my machine even if there is 1000 `x = x * x`.
