### ISSUE TITLE
Print IterDomain's extents inline when detail level is ComputeOnly

### ISSUE THREAD

**Issue by tlemo** [csarofeen/pytorch#148]
1. Right now we print the extent Vals directly, which makes it hard to correlate values across the IR:
![graphviz](https://user-images.githubusercontent.com/13824553/86817532-01429b80-c03a-11ea-8b45-785aad83e84d.png)

2. Also, for ComputeOnly we don't need to generate a graphviz cluster

**Comment by csarofeen** [comment]
Closing as stale.
