### ISSUE TITLE
Missing syncthreads

### ISSUE THREAD

**Issue by naoyam** [csarofeen/pytorch#1510]
Some of the shift/gather tests are failing non-deterministically due to missing syncthreads.

For example, in `FusionMaxPoolingStrided`, there must be syncthreads after loading to `T3`, but that's missing.

Correct:

```
        #pragma unroll
        for(nvfuser_index_t i61 = 0; i61 < 5; ++i61) {
          #pragma unroll
          for(nvfuser_index_t i62 = 0; i62 < 5; ++i62) {
            T3[(((((nvfuser_index_t)threadIdx.y) * 3) + i61) * 98) + ((((nvfuser_index_t)threadIdx.x) * 3) + i62)]
               = T0[(((nvfuser_index_t)blockIdx.x) * T0.stride[0]) + ((((((i43 * 8) + ((nvfuser_index_t)threadIdx.y)) * 3) + i61) - 1) * T0.stride[1]) + ((((((i45 * 32) + ((nvfuser_index_t)threadIdx.x)) * 3) + (i62 + nvfuser_zero)) - 1)
 * T0.stride[2])];
          }
        }
        NVFUSER_UPDATE_MAGIC_ZERO
        __barrier_sync(0);
```

TOT:

```
        #pragma unroll
        for(nvfuser_index_t i61 = 0; i61 < 5; ++i61) {
          #pragma unroll
          for(nvfuser_index_t i62 = 0; i62 < 5; ++i62) {
            T3[(((((nvfuser_index_t)threadIdx.y) * 3) + i61) * 98) + ((((nvfuser_index_t)threadIdx.x) * 3) + i62)]
               = T0[(((nvfuser_index_t)blockIdx.x) * T0.stride[0]) + ((((((i43 * 8) + ((nvfuser_index_t)threadIdx.y)) * 3) + i61) - 1) * T0.stride[1]) + ((((((i45 * 32) + ((nvfuser_index_t)threadIdx.x)) * 3) + (i62 + nvfuser_zero)) - 1)
 * T0.stride[2])];
          }
        }
        NVFUSER_UPDATE_MAGIC_ZERO
        float T1[((1 * 3) * 3)];
```

Not sure why yet, but this bug is introduced with #1484.

**Comment by csarofeen** [comment]
Are you sure a sync there is required? It looks to me in this example that each thread writes everything it ends up reading, it looks like it does this somewhat redundantly, but I don't see any thread reading from SMEM something it didn't write.

I do see consistent failures though with:
```
// [  FAILED  ] NVFuserTest.FusionConv4x4Pad1x1Stride4_CUDA
// [  FAILED  ] NVFuserTest.FusionConv2DStaticStrided_CUDA
```
So I'm really curious if `MaxPoolingStrided` does consistently fail for you.

**Comment by csarofeen** [comment]
So in:
`NVFuserTest.FusionConv4x4Pad1x1Stride4_CUDA` there's something quite similar to `MaxPoolingStrided`:
The indexing on T7 is writes:
```.cpp
T7[(((nvfuser_index_t)threadIdx.z) * 1273) + (((((nvfuser_index_t)threadIdx.y) * 4) + i109) * 67) + ((((nvfuser_index_t)threadIdx.x) * 4) + i110)]
```
and reads:
```.cpp
T7[(((nvfuser_index_t)threadIdx.z) * 1273) + ((((((nvfuser_index_t)threadIdx.y) * 4) + 1) + (i103 - 1)) * 67) + (((((nvfuser_index_t)threadIdx.x) * 4) + 1) + (i104 - 1))];
```

Where `i109` and `i110` is in the range `[0,6]` and `i103` and `i104` is in the range `[0,3]`

So to me it seems the reads are exclusively positioned within the writes, but it is failing to validate.

Note T7's RHS for its write is:
```.cpp
T0[(((i99 * 2) + ((nvfuser_index_t)threadIdx.z)) * T0.stride[0]) + ((((((i93 * 4) + ((nvfuser_index_t)threadIdx.y)) * 4) + i109) - 1) * T0.stride[1]) + ((((((i95 * 16) + ((nvfuser_index_t)threadIdx.x)) * 4) + (i110 + nvfuser_zero)) - 1) * T0.stride[2])]
```

**Comment by csarofeen** [comment]
Okay, it's not the RAW sync, it's the WAR sync. Since each thread is writing the values it's going to read, RAW is not an issue. The issue is that the threads are overlapping, and they have an outer iteration, so one thread could replace the value of another thread (overwriting its result) before the other thread has finished reading.

**Comment by csarofeen** [comment]
We need a mechanism to detect when threads may have overlapping sections of a memory space. This of course can only happy with shift or gather, we might simply assume any shift/gather expression can do this however that is a conservative assumption as it requires the thread bindings to be on the dimensions the window is being applied. Thoughts @naoyam?
