### ISSUE TITLE
Support fuser::Allocate with symbolic sizes

### ISSUE THREAD

**Issue by tlemo** [csarofeen/pytorch#158]
Right now, we require the allocation size to be a constant. Since we bind the input sizes, we can relax this limitation with a bit of help from the expression evaluator: 

1. try evaluate the allocation sizes.
2. if we can evaluate the size, use it to calculate a total size for scratch buffer needed by the kernel
3. allocate the scratch buffer host side, and pass it as argument to the kernel
4. kernel will place allocations within this scratch buffer

A basic solution would just add up all the individual allocations to calculate the scratch buffer size. A more sophisticated version could track the lifetimes of the scratch buffers and reuse the same space if they don't overlap (ie. pack the allocations)

We could start with the simple solution, and add the packing in follow up iteration.

**Comment by csarofeen** [comment]
I think this restriction has been lifted with global allocations and Ryan's work on https://github.com/csarofeen/pytorch/pull/304

**Comment by rdspring1** [comment]
#325 enables global intermediate buffers with symbolic sizes
