### ISSUE TITLE
Unswitch + Unroll parallelization causes incorrect results with transpose scheduler on non-vectorize sizes

### ISSUE THREAD

**Issue by rdspring1** [csarofeen/pytorch#1595]
Uncommenting [the unswitch and unroll parallelism](https://github.com/csarofeen/pytorch/blob/rds_transpose/torch/csrc/jit/codegen/cuda/scheduler/transpose.cpp#L663-L667) will cause the following tests fail:

- [  FAILED  ] NVFuserTest.FusionTransposeSchedulerVerticalBinarySwap_CUDA
- [  FAILED  ] NVFuserTest.FusionTransposeSchedulerVerticalUnary_CUDA
- [  FAILED  ] NVFuserTest.FusionTransposeSchedulerMatrixInner_CUDA
- [  FAILED  ] NVFuserTest.FusionTransposeSchedulerTensorInput_CUDA
- [  FAILED  ] NVFuserTest.FusionTransposeSchedulerInnerMostPowerSet_CUDA
- [  FAILED  ] NVFuserTest.FusionTransposeSchedulerPointwise_CUDA

Validation fails:
```
Validation error in output 0 on line 1173 in file ../torch/csrc/jit/codegen/cuda/test/test_gpu_view.cpp.
  Detected abs error of: 1.53378
    absolute tolerance was set to 1.51992e-06
    and relative tolerance set to 2.23704e-06
```

Applying the `PYTORCH_NVFUSER_DISABLE_PREDICATE_ELIMINATION` flag did not fix the issue.

### Versions

`rds_transpose` branch at commit 808e73266865de84b7dab247b3fce1af99798eae

**Comment by naoyam** [comment]
Do they fail when only either of the unswitch or unroll is used? Or do they fail only when both of them are used?

**Comment by rdspring1** [comment]
Both cases fail. Only when unswitch and unroll are disabled will the tests pass for non-vectorized sizes.

**Comment by naoyam** [comment]
OK, I'll look into it.

**Comment by naoyam** [comment]
The tests don't seem to fail when only the unswitch is enabled. Is it different on your system?

**Comment by rdspring1** [comment]
The failure can be shape dependent. With only unswitch enabled and the current sizes, it passes with my 3090 but fails on the A100.

https://github.com/csarofeen/pytorch/blob/rds_transpose/torch/csrc/jit/codegen/cuda/test/test_gpu_view.cpp#L939-L944

**Comment by naoyam** [comment]
Thanks. No idea why, but looks like there's a sync problem. Here's the generated code from `TransposeSchedulerPointwise` with no unswitch and unroll:

```
 for(nvfuser_index_t i99 = 0; i99 < (ceilDiv((ceilDiv((ceilDiv((32 * 32), ((nvfuser_index_t)blockDim.x))), 4)), 1)); ++i99) {
    #pragma unroll
    for(nvfuser_index_t i102 = 0; i102 < 4; ++i102) {
      int64_t i376;
      i376 = (((i99 * 4) + (i102 + nvfuser_zero)) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x);
      int64_t i196;
      i196 = ((((nvfuser_index_t)blockIdx.x) / (ceilDiv(T0.size[0], 32))) * 32) + (((((i99 * 4) + (i102 + nvfuser_zero)) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) / 32);
      int64_t i193;
      i193 = ((((nvfuser_index_t)blockIdx.x) % (ceilDiv(T0.size[0], 32))) * 32) + (((((i99 * 4) + (i102 + nvfuser_zero)) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) % 32);
      float T6[1];
      T6[0] = 0;
      if ((((i196 < T0.size[1]) && (i193 < T0.size[0])) && (i376 < (32 * 32)))) {
        T6[0]
           = T1[(i196 * T0.size[0]) + i193];
      }
      float T2[1];
      T2[0] = 0;
      __barrier_sync(0);
      if ((((i196 < T0.size[1]) && (i193 < T0.size[0])) && (i376 < (32 * 32)))) {
        T2[0]
           = T8[((((((((i99 * 4) + i102) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) / 32) + (((((i99 * 4) + i102) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) % 32)) % 32) * 32) + (((((i99 * 4) + i102) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) / 32)];
      }
      float T3[1];
      T3[0]
        = T2[0]
        + T6[0];
      float T5[1];
      T5[0]
         = relu(T3[0]);
      if ((((i196 < T0.size[1]) && (i193 < T0.size[0])) && (i376 < (32 * 32)))) {
        T4[(i196 * T0.size[0]) + i193]
           = T5[0];
      }
    }
    NVFUSER_UPDATE_MAGIC_ZERO
  }
```

`T8` is on shared memory and needs a sync before reads. With `tv->axis(-2)->parallelize(ParallelType::Unroll)`, though, the generated code is:

```
    if (((((((((nvfuser_index_t)blockIdx.x) / (ceilDiv(T0.size[0], 32))) * 32) + (((((i99 * 4) + 3) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) / 32)) < T0.size[1]) && ((((((nvfuser_index_t)blockIdx.x) % (ceilDiv(
T0.size[0], 32))) * 32) + (((((i99 * 4) + 3) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) % 32)) < T0.size[0])) && (((((i99 * 4) + 3) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) < (32 * 32)))
) {
      #pragma unroll
      for(nvfuser_index_t i102 = 0; i102 < 4; ++i102) {
        int64_t i253;
        i253 = ((((nvfuser_index_t)blockIdx.x) / (ceilDiv(T0.size[0], 32))) * 32) + (((((i99 * 4) + (i102 + nvfuser_zero)) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) / 32);
        int64_t i250;
        i250 = ((((nvfuser_index_t)blockIdx.x) % (ceilDiv(T0.size[0], 32))) * 32) + (((((i99 * 4) + (i102 + nvfuser_zero)) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) % 32);
        T6[i102]
           = T1[(i253 * T0.size[0]) + i250];
        T2[i102]
           = T8[((((((((i99 * 4) + i102) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) / 32) + (((((i99 * 4) + i102) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) % 32)) % 32) * 32) + (((((i99 * 4) + i102) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) / 32)];
        T3[i102]
          = T2[i102]
          + T6[i102];
        T5[i102]
           = relu(T3[i102]);
        T4[(i253 * T0.size[0]) + i250]
           = T5[i102];
        __barrier_sync(0);
      }
      NVFUSER_UPDATE_MAGIC_ZERO
    } else {
      ... // continue with the predicated block
```

As you can see, `__barrier_sync(0)` is moved to the end of the loop block. This doesn't seem to happen with `unswitch`.

**Comment by naoyam** [comment]
In any case, I think the placement of the sync should be fixed. Without unroll, we do insert the sync just before the reads of `T8`, which is correct, but it doesn't need to be executed at each loop iteration. It should be placed outside of the `i99` loop.

**Comment by naoyam** [comment]
There appears something strange with `T8` indexing: `T8[((((((((i99 * 4) + i102) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) / 32) + (((((i99 * 4) + i102) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) % 32)) % 32) * 32) + (((((i99 * 4) + i102) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) / 32)];`. I'm looking into this, but still don't know why it has `% 32)) %32)`.

**Comment by naoyam** [comment]
> There appears something strange with `T8` indexing: `T8[((((((((i99 * 4) + i102) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) / 32) + (((((i99 * 4) + i102) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) % 32)) % 32) * 32) + (((((i99 * 4) + i102) * ((nvfuser_index_t)blockDim.x)) + ((nvfuser_index_t)threadIdx.x)) / 32)];`. I'm looking into this, but still don't know why it has `% 32)) %32)`.

OK, that's because it's swizzled, so that should be fine.

**Comment by naoyam** [comment]
Filed an issue on sync placement: #1598

**Comment by naoyam** [comment]
Filed another issue on RAW sync and unroll: #1599 

Those two issues are not directly related to transpose, but I believe this issue is caused by them.

**Comment by naoyam** [comment]
The tests pass with #1600.

**Comment by naoyam** [comment]
Closes this issue as the fix PR is merged. Please reopen if they still fail.
