### ISSUE TITLE
Implement `atan2` and `bitwise_{xor, and, or, not}` operations for python frontend.

### ISSUE THREAD

**Issue by kevinstephano** [csarofeen/pytorch#1632]
### 🚀 The feature, motivation and pitch

There is a request to add this operations and plug them into the NVFuser python frontend.

Note, the development on the python frontend is currently done directly in upstream.

This is an example of the Frontend.  
https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/codegen/cuda/python_frontend/examples/python_example.py

It is likely you can just add a single line per op here with this Macro:
https://github.com/pytorch/pytorch/blob/0708630d9f30210b0a51d13558ad173da630ef95/torch/csrc/jit/codegen/cuda/python_frontend/python_bindings.cpp#L297-L339

**Comment by zasdfgbnm** [comment]
Reopening as there are still `bitwise_{xor, and, or, not}` missing.

**Comment by kevinstephano** [comment]
Xiang, are you still working on the bitwise operands?

**Comment by zasdfgbnm** [comment]
Yes, I am. I was just waiting for the reland of my reverted PR https://github.com/pytorch/pytorch/pull/76769, which is relanded last Saturday.

**Comment by zasdfgbnm** [comment]
Related PR for bitwise ops:
https://github.com/pytorch/pytorch/pull/77146
https://github.com/pytorch/pytorch/pull/77158
