### ISSUE TITLE
Python Frontend ran into an issue with binary ops and tensors of double and half

### ISSUE THREAD

**Issue by kevinstephano** [csarofeen/pytorch#1633]
### 🐛 Describe the bug

It was reported that there was an error with the combination of a Half Tensor input and a Double Tensor input via the python frontend.  Development needs to be done on Upstream direct PRs.

This is an example:
```
def foo(a, b):
  return torch.add(a, b)

traced_foo = make_traced(foo)

a = torch.randn((2, 2), device='cuda', dtype=torch.double)
b = torch.randn((2, 2), device='cuda', dtype=torch.half)
result = traced_foo(a, b, executor='nvfuser')
torch.cuda.synchronize()
```

This was the error seen:
```
RuntimeError: Illegal Cast value from  DataType: __half to DataType: double
```

This should probably be turned into a python frontend example.  You can look here for guidance:
https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/codegen/cuda/python_frontend/examples/python_example_fp16.py

Christian mentioned looking here:
https://github.com/csarofeen/pytorch/blob/b98becbcb1d5be0d681577ca8d83979adda43b0d/torch/csrc/jit/codegen/cuda/type.cpp#L723

Pre-Volta there wasn't converts from FP16 to FP64, you had to go through fp32, but it should be there for Volta and beyond.  

### Versions

TOT

**Comment by rdspring1** [comment]
Cast issue is being addressed in https://github.com/pytorch/pytorch/pull/76605

**Comment by rdspring1** [comment]
The PR was merged into upstream.
