### ISSUE TITLE
Unsqueeze hits assert

### ISSUE THREAD

**Issue by jjsjann123** [csarofeen/pytorch#1689]
### 🐛 Describe the bug

Unsqueeze hits assert on upstream. Issue opened here: https://github.com/pytorch/pytorch/issues/76883

Judging by the error message, I think there's something wrong with our parser translating unsqueeze. Not sure if the segfault in the second example is caused by the same reason (invalid graph). But David's fix that prevents segfault looks right to me: https://github.com/pytorch/pytorch/pull/77010

Opening the issue to track the bug since upstream issue has been closed (we disabled unsqueeze).

### Versions

Repros on upstream/master as well as our devel: f952365e4dd8436c1f3ac0f02f4481ce32ebb03d

**Comment by naoyam** [comment]
@jjsjann123 Merged two fixes. Let me know if it still fails.

**Comment by jjsjann123** [comment]
Looks like both examples run fine now :tada: 

Thanks for fixing this~~
