### ISSUE TITLE
ops.alias failing somewhere in timm

### ISSUE THREAD

**Issue by csarofeen** [csarofeen/pytorch#1700]
### 🐛 Describe the bug

PYTORCH_NVFUSER_DISABLE=fallback TIMM_BENCHMARK_ENABLE_TORCHDYNAMO=1 python pytorch-image-models/benchmark.py --bench train --amp --channels-last -b 64 --model tf_mobilenetv3_large_075
WARNING: Overriding precision to 'amp' since --amp flag set.
Benchmarking in amp precision. NHWC layout. torchscript disabled
Model tf_mobilenetv3_large_075 created, param count: 3993528
Running train benchmark on tf_mobilenetv3_large_075 for 40 steps w/ input size (3, 224, 224) and batch size 64.
WARNING: "x->nDims() == sizes.size() INTERNAL ASSERT FAILED at "../torch/csrc/jit/codegen/cuda/ops/alias.cpp":143, please report a bug to PyTorch. " while running benchmark. Reducing batch size to 64 for retry.

### Versions

Nightly (functorch compilation is broken atm but can be worked around by using the commit **BEFORE**
`71ba8238d93857ff7dec1b627d51814027220db5 `

**Comment by csarofeen** [comment]
Looks like it's `prim::squeeze_copy` running with `TIMM_BENCHMARK_NVFUSER_SKIP_NODE_KINDS="aten::squeeze;prim::squeeze_copy"` works fine. @jjsjann123 is squeeze disabled for 1.12?

**Comment by jjsjann123** [comment]
Yes they are.
We disabled `xxx_copy` decomposition for all alias ops in upstream. So you won't have them in the first place: https://github.com/pytorch/pytorch/blob/168dc70faf9764417a7e41a14bf2f4e15a7f3e4a/torch/csrc/jit/codegen/cuda/graph_fuser.cpp#L2101-L2106

**Comment by jjsjann123** [comment]
Let's keep this issue open since the bug is real. I'll try to get a minimal python repro out of it and trace the fix on that~

**Comment by csarofeen** [comment]
Thanks. @rdspring1 to follow up after 1.12 settles.

**Comment by rdspring1** [comment]
@csarofeen I wasn't able to reproduce this `squeeze` issue on latest upstream.

**Comment by IvanYashchuk** [comment]
Were you able to reproduce the problem with some older commits from around April-May?

What does `TIMM_BENCHMARK_ENABLE_TORCHDYNAMO=1` do? I cannot find any references in the code.

**Comment by jjsjann123** [comment]
@IvanYashchuk That's from Xiao's edit to enable torchDynamo:  https://github.com/xwang233/pytorch-image-models/blob/master-patched/benchmark.py#L27-L29

**Comment by csarofeen** [comment]
> Were you able to reproduce the problem with some older commits from around April-May?

@rdspring1 I think this is a good point, can we go back (shouldn't even have to go back too far) to reproduce this and try to figure out what the issue was?

**Comment by rdspring1** [comment]
It can be tricky to find a functorch commit compatible with a random commit in our branch. I will look into commits around the 1.12 cutoff.
