### ISSUE TITLE
fragmented layer norm hits nvfuser codegen error

### ISSUE THREAD

**Issue by jjsjann123** [csarofeen/pytorch#1713]
### 🐛 Describe the bug

Hitting error:
```
RuntimeError: false INTERNAL ASSERT FAILED at "../torch/csrc/jit/codegen/cuda/executor.cpp":236, please report a bug to PyTorch. Allocations must be based on constant integers for local memory. However, found: T24_l[ sbblockIdx.x167{( ceilDiv(( ceilDiv(( ceilDiv(1, 4) ), blockDim.x) ), 1) )}, sbthreadIdx.x166{blockDim.x}, iS174{( ceilDiv(( ceilDiv(( ceilDiv(T0.size[0], blockDim.y) ), 1) ), gridDim.y) )}, sbUS168{1}, sbS164{4}, iblockIdx.y173{gridDim.y}, ithreadIdx.y170{blockDim.y}, iUS172{1} ], T6_l[ sbblockIdx.x143{( ceilDiv(( ceilDiv(( ceilDiv(1, 4) ), blockDim.x) ), 1) )}, sbthreadIdx.x142{blockDim.x}, iS150{( ceilDiv(( ceilDiv(( ceilDiv(T0.size[0], blockDim.y) ), 1) ), gridDim.y) )}, sbUS144{1}, sbS140{4}, iblockIdx.y149{gridDim.y}, ithreadIdx.y146{blockDim.y}, iUS148{1} ],  have dynamic allocations but are placed in local memory
```

From Natalia's example here:
```
import torch
from functorch.compile import memory_efficient_fusion, clear_compile_cache, aot_function, min_cut_rematerialization_partition


#torch._C._jit_set_nvfuser_single_node_mode(True)
def print_compile(fx_g, _):
    print(fx_g.code)
    return fx_g



def layer_norm(x, weight, bias):
    dim = -1
    eps = 1e-5
    #var = torch.var(x, dim, unbiased=False, keepdim=True) #nvfuser hates it
    mean = torch.mean(x, dim, keepdim=True)
    centered = x - mean
    var = torch.sum(centered * centered, dim, keepdim=True )/ x.size(-1)
    rvar = 1./torch.sqrt(var+eps)
    normed = (x-mean) * rvar
    return normed * weight + bias, rvar, mean

def simple_norm(x):
    x = x + 1
    s = x.sum(-1, keepdim=True)
    return s * x

device = "cuda"
ln_size = 1024
scripted_ln = torch.jit.script(layer_norm)
x=torch.randn(204800, ln_size, device=device, requires_grad=True)
weight = torch.randn(ln_size, device=device, requires_grad=True)
bias = torch.rand_like(weight, requires_grad=True)
gO = torch.rand_like(x)


opt_fn = aot_function(layer_norm, print_compile, partition_fn = min_cut_rematerialization_partition)

for _ in range(4):
    out=layer_norm(x, weight, bias)
    #print(out.size(), gO.size())
    out[0].backward(gO)


out = opt_fn(x, weight, bias)
#print(out.size(), gO.size())
out[0].backward(gO)

opt_fn = memory_efficient_fusion(
    layer_norm
)

with torch.jit.fuser("fuser2"):
    for _ in range(4):
        x.grad=None
        weight.grad=None
        bias.grad=None
        out=opt_fn(x, weight, bias)
        out[0].backward(gO)
```

### Versions

I'm able to get a repro in our nightly containers. (since the repro requires functorch, it is probably easier to repro there for you as well)

Container I used: gitlab-master.nvidia.com:5005/dl/pytorch/update-scripts:jit-cuda11-latest
image id (db33a052a269) <- you shouldn't need to grab this exact image, if it doesn't repro on master that means it's magically fixed already..

**Comment by jjsjann123** [comment]
cc'ing @ngimel

**Comment by shmsong** [comment]
Seems to be a CPP repro if it helps:
```cpp


TEST_F(NVFuserTest, FusionRepro1713_CUDA) {
  Fusion fusion;
  FusionGuard fg(&fusion);

  auto tv0 = makeSymbolicTensor(2);
  auto tv1 = makeSymbolicTensor(2);
  auto tv2 = makeSymbolicTensor(1);
  fusion.addInput(tv0);
  fusion.addInput(tv1);
  fusion.addInput(tv2);
  auto tv3 = broadcast(tv2, {false, true});
  
  auto tv4 = add(tv3, tv0);

  auto tv5 = add(tv3, tv1);
  auto tv6 = sum(tv5, {0});
  fusion.addOutput(tv4);
  fusion.addOutput(tv6);

  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  at::Tensor t0 = at::randn({1024, 204800}, options);
  at::Tensor t1 = at::randn({1024, 204800}, options);
  at::Tensor t2 = at::randn({1024}, options);

  auto reduction_params = getReductionHeuristics(&fusion, {t0, t1, t2});
  TORCH_CHECK(reduction_params, "Reduction schedule was not generated!");
  scheduleReduction(&fusion, reduction_params.value());
  
  auto lparams = reduction_params.value().lparams;

  FusionExecutor fe;
  fe.compileFusion(&fusion, {t0, t1, t2},lparams);
  auto cg_outputs = fe.runFusion({t0, t1, t2},lparams);
}

```

original failing segment:
```
g{(reduction)
inputs: 
T0_g[ iS0{i1}, iS1{i2} ] float
T1_g[ iS2{i3}, iS3{i4} ] float
T4_g[ iS8{i9}, iS9{i10} ] float
T5_g[ iS10{i11}, sbS11{1} ] float
outputs: 
T7_g[ iS14{i9}, iS15{i10} ] float
T21_g[ bS42{1}, iS43{i2} ] float


T6_g[ iS12{i11}, sbS13{1} ]
   = T5_g[ iS10{i11}, sbS11{1} ]
   * double(1);
T7_g[ iS14{i9}, iS15{i10} ]
   = T4_g[ iS8{i9}, iS9{i10} ]
   * T6_g[ iS12{i11}, sbS13{1} ];
T18_g[ iS36{i3}, iS37{i4} ]
   = T1_g[ iS2{i3}, iS3{i4} ]
   * T6_g[ iS12{i11}, sbS13{1} ];
T19_g[ iS38{i1}, iS39{i2} ]
   = T0_g[ iS0{i1}, iS1{i2} ]
   * T18_g[ iS36{i3}, iS37{i4} ];
T20_g[ rS40{i1}, iS41{i2} ]
   = reduction( T19_g[ iS38{i1}, iS39{i2} ], op = add, initial value = double(0), allreduce = 0 )
T21_g[ bS42{1}, iS43{i2} ]
   = broadcast( T20_g[ rS40{i1}, iS41{i2} ] )
}
```

**Comment by shmsong** [comment]
@naoyam 

Problem seemed to be that the broadcast in `tv3` was concretized twice to un-mapped id's. 

I'm not sure if we want to support computeAt in this case. We could either segment them apart or try to support this kind of broadcast inlining.

**Comment by ngimel** [comment]
In python 
```
def fn(x0,x1,x2):
    x3 = x2.unsqueeze(-1)
    x4=x3+x0
    x5=x3+x1
    x6=x5.sum(0)
    return x4, x6

device = "cuda"
x0=torch.randn(1024, 204800, device=device)
x1=torch.rand_like(x0)
x2=torch.randn(1024, device=device)


scripted = torch.jit.script(fn)
with torch.jit.fuser("fuser2"):
    for _ in range(4):
        out=scripted(x0,x1,x2)
```
the above fails, however, if I explicitly broadcast x2 as `x3=x2.unsqueeze(-1).expand_as(x0)` it works and generates a reasonable kernel, so the problem maybe not computeAt, but handling explicitly (correct dimension, stride=0) vs implicitly broadcast tensors - why can't the latter be turned into former?

**Comment by ngimel** [comment]
Also, since this happens with just scripting not particularly complicated functions (no AOT), how widespread do you think this bug is, and will users be hitting it a lot if nvfuser is turned by default? Like, is it any broadcast addition followed by reduction, or broadcasted tensor should be used in multiple places to hit this?

**Comment by naoyam** [comment]
The tricky part of `fn` is nvfuser doesn't know whether `x0` and `x1` has the same shape. Their first axes are fine as that of `x2` is not a broadcast, so we can deduce all of them have the same extent. However, since the second axis of `x2` is a broadcast, and there's no operation using both `x0` and `x1`, we conservatively assume they may have different extents, which makes the inlining approach used for this pattern of fusions fail to do what's supposed to be done.

Looks like we implement `expand_as` as actual expansion of a tensor, so  with `x3=x2.unsqueeze(-1).expand_as(x0)`, `x3` has no longer any broadcast axis. This removes the above ambiguity, so we don't need to be conservative, and the inlinig approach just works fine.

To be more specific, this error happens when:

- A tensor has a broadcast inner axis.
- That tensor is reduced on an outer axis
- That tensor is used with two tensors that may have different concrete sizes.

@shmsong Yes, we could avoid this problem by segmenting the fusion, but that seems just inefficient as there should be no hard constraint that the fusion can't be formed as a single CUDA kernel.

**Comment by naoyam** [comment]
We fixed this issue by segmenting the fusion so that the broadcast axis is only used with a unique non-broadcast axis. This may not be ideal in terms of performance, but should avoid the problem with the scheduler.
