### ISSUE TITLE
Support 0 sized tensors

### ISSUE THREAD

**Issue by IvanYashchuk** [csarofeen/pytorch#1752]
### 🚀 The feature, motivation and pitch

PyTorch supports 0-sized tensors and test generation with OpInfos often includes such inputs. Some users also explicitly asked for 0-sized tensors to just work and not error out where it makes sense.

It would be nice not to special case zeros in the shape of a tensor and make it work with nvFuser.
Currently, assert would be triggered from here:
https://github.com/csarofeen/pytorch/blob/8a69aa320bd7629e1709fe5ceb7104d2c88ec84c/torch/csrc/jit/codegen/cuda/executor_utils.cpp#L784

**Comment by naoyam** [comment]
Just want to make sure I understand this correctly, if a tensor has a size-0 dimension, does it mean the tensor is empty?

**Comment by IvanYashchuk** [comment]
Yes, if a tensor has a size-0 dimension, then `tensor.numel() == 0`, and there's nothing to iterate on.

**Comment by IvanYashchuk** [comment]
Also reported upstream https://github.com/pytorch/pytorch/issues/80231.

**Comment by jjsjann123** [comment]
So zero sized tensor basically is a no op. We only needed to do proper shape inference and allocate output tensor with proper size. Would this be something that we can support relatively easily? tagging @naoyam for a rough estimation of workload.

For prim integration, I think partitioning logic might be something easy to work with. But for our python API, this makes a lot more sense and would be nice to have.

**Comment by naoyam** [comment]
Just copying an internal chat for reference. We'll revisit this post 1.13.

> In terms of implementation probably we want a "null" scheduler that will take all tensors of size-0 and do nothing to them in scheduling.
