### ISSUE TITLE
The interval for torch::jit::fuser::cuda::randlike is not the same as for torch.rand_like

### ISSUE THREAD

**Issue by IvanYashchuk** [csarofeen/pytorch#1807]
### 🐛 Describe the bug

See the discussion here https://github.com/csarofeen/pytorch/issues/1799#issuecomment-1175512146.

Turns out nvfuser's randlike function generates "1.0" in uniform samples while in PyTorch uniform distribution is sampled on the interval [0.0, 1.0), "0.0" is included, "1.0" is excluded.

I think nvfuser's random numbers should be changed to sample on [0.0, 1.0) interval. `uniform` and `uniformf` functions are implemented [here](https://github.com/csarofeen/pytorch/blob/devel/torch/csrc/jit/codegen/cuda/runtime/random_numbers.cu), and used for `randLike` device functions: https://github.com/csarofeen/pytorch/blob/fa4e6a4739a9daaa0e4111fb4730704d79c91010/torch/csrc/jit/codegen/cuda/runtime/helpers.cu#L302-L308
We could replace generated samples of 1.0 with 0.0:
```cpp
 __device__ float randLikef(Philox& rnd) { 
   float sample = uniformf(rnd());
   return sample == 1.0 ? 0.0 : sample;
 } 
```

### Versions

devel branch

**Comment by jjsjann123** [comment]
I guess with #1804 this is considered as fixed?

**Comment by IvanYashchuk** [comment]
Yes, thank you!
