### ISSUE TITLE
TIMM Dynamic size Local memory allocation

### ISSUE THREAD

**Issue by rdspring1** [csarofeen/pytorch#1844]
### 🐛 Describe the bug

Fusion fails with fallback path with channels_last + amp + batch_size > 1

Steps to reproduce:
`PYTORCH_NVFUSER_DISABLE_FALLBACK=1 python benchmark.py --bench train --model rexnet_100 --img-size 224 -b 2 --amp --torchscript --channels-last --no-retry`

Failing networks:
- volo_d1_224
- xcit_tiny_12_p16_224
- xcit_nano_12_p8_224_dist
- xcit_tiny_24_p16_224_dist
- xcit_small_12_p16_224
- xcit_nano_12_p16_224
- xcit_medium_24_p16_224_dist
- crossvit_9_240
- crossvit_tiny_240
- crossvit_18_240
- crossvit_small_240
- crossvit_base_240

General Error:

> RuntimeError: false INTERNAL ASSERT FAILED at "../torch/csrc/jit/codegen/cuda/executor.cpp":236, please report a bug to PyTorch. Allocations must be based on constant integers for local memory. 
> However, found: **T12_l**[ iblockIdx.x170{( ceilDiv(T0.size[2], blockDim.x) )}, ithreadIdx.x171{blockDim.x}, iS174{( ceilDiv(( ceilDiv(T0.size[0], blockDim.y) ), 1) )}, ithreadIdx.y173{blockDim.y}, iUS175{1}, bS37{1} ], T13_l[ iblockIdx.x164{( ceilDiv(T0.size[2], blockDim.x) )}, ithreadIdx.x165{blockDim.x}, iS168{( ceilDiv(( ceilDiv(T0.size[0], blockDim.y) ), 1) )}, ithreadIdx.y167{blockDim.y}, iUS169{1}, bS40{1} ], T14_l[ iblockIdx.x158{( ceilDiv(T0.size[2], blockDim.x) )}, ithreadIdx.x159{blockDim.x}, iS162{( ceilDiv(( ceilDiv(T0.size[0], blockDim.y) ), 1) )}, ithreadIdx.y161{blockDim.y}, iUS163{1}, bS43{1} ], T15_l[ iblockIdx.x152{( ceilDiv(T0.size[2], blockDim.x) )}, ithreadIdx.x153{blockDim.x}, iS156{( ceilDiv(( ceilDiv(T0.size[0], blockDim.y) ), 1) )}, ithreadIdx.y155{blockDim.y}, iUS157{1}, bS46{1} ],  have **dynamic allocations but are placed in local memory**.

### Versions

1. nvfuser devel branch

**Comment by rdspring1** [comment]
Reproducer

```c++
/*
with prim::CudaFusionGroup_4 = graph(%5 : Float(2, 1, 768, strides=[768, 768, 1], requires_grad=0, device=cuda:0),
       %8 : Float(2, 1, 768, strides=[768, 768, 1], requires_grad=0, device=cuda:0),
       %9 : Bool(2, 1, 768, strides=[768, 768, 1], requires_grad=0, device=cuda:0),
       %10 : float):
   %1 : int[] = prim::Constant[value=[768]]()
   %6 : str = prim::Constant[value="none"]()
   %grad_input.36 : Float(2, 1, 768, strides=[768, 768, 1], requires_grad=0, device=cuda:0) = aten::native_dropout_backward(%8, %9, %10) # <string>:50:29
   %7 : Float(2, 1, 768, strides=[768, 768, 1], requires_grad=0, device=cuda:0) = aten::gelu_backward(%grad_input.36, %5, %6) # <string>:112:23
   %grad_bias.14 : Float(768, strides=[1], requires_grad=0, device=cuda:0) = aten::_grad_sum_to_size(%7, %1) # <string>:70:31
   return (%grad_bias.14, %7)
*/

TEST_F(NVFuserTest, FusionIssueRepro1844_CUDA) {
  auto fusion = std::make_unique<Fusion>();
  FusionGuard fg(fusion.get());

  std::vector<int64_t> shape = {2, 1, 768};
  std::vector<int64_t> sum_to_shape = {768};
  std::vector<int64_t> sum_to_axes = {0, 1};
  double kProb = 0.5;

  std::vector<Int*> sum_to_symb;
  std::transform(
      sum_to_shape.begin(),
      sum_to_shape.end(),
      std::back_inserter(sum_to_symb),
      [](int s) -> Int* { return IrBuilder::create<Int>(s); });

  TensorView* tv0 = makeContigConcreteTensor(shape);
  TensorView* tv1 = makeContigConcreteTensor(shape);
  TensorView* tv2 = makeContigConcreteTensor(shape, DataType::Bool);

  fusion->addInput(tv0);
  fusion->addInput(tv1);
  fusion->addInput(tv2);

  Double* prob = IrBuilder::create<Double>(kProb);
  auto grad_input = dropout_backward(tv1, tv2, prob);
  auto grad_gelu = gelu_backward(grad_input, tv0);
  auto grad_bias = sum_to(grad_gelu, sum_to_symb);

  fusion->addOutput(grad_gelu);
  fusion->addOutput(grad_bias);

  const auto options =
      at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  const auto mask_options =
      at::TensorOptions().dtype(at::kBool).device(at::kCUDA, 0);
  at::manual_seed(0);

  at::Tensor a = at::randn(shape, options);
  at::Tensor b = at::randn(shape, options);
  at::Tensor c = at::randn(shape, options);
  auto mask = at::gt(c, 0.0f);
  std::vector<IValue> aten_inputs = {a, b, mask};

  FusionExecutorCache executor_cache(std::move(fusion));
  auto cg_outputs = executor_cache.runFusionWithInputs(aten_inputs);

  auto dinput = at::native_dropout_backward(b, mask, kProb);
  auto dgelu = at::gelu_backward(dinput, a, "none");
  auto dbias = dgelu.sum(sum_to_axes);

  testValidate(
      executor_cache.fusion(),
      cg_outputs,
      aten_inputs,
      {dgelu, dbias},
      __LINE__,
      __FILE__);
}
```

**Comment by rdspring1** [comment]
@zasdfgbnm Could this be an issue with computeAt + scheduling? I was able to reproduce the issue at ToT of nvfuser devel branch but not ToT of pytorch master.

**Comment by zasdfgbnm** [comment]
Thanks for debugging and minimum repro! I will take a look.

**Comment by zasdfgbnm** [comment]
This is definitely an issue of inlining. See the dumpped fusion ir math change at: https://editor.mergely.com/agO2HftN/, the CA position of some tensors is lost.

**Comment by zasdfgbnm** [comment]
I have checked this issue. It seems to be because the set that computeAt propagates to has changed. That computeAt is used somewhere inside `multiReductionInliner`. Fortunately, @csarofeen's is modifying this function in https://github.com/csarofeen/pytorch/pull/1845. I checked his branch, and this bug is magically fixed 🤩🤩🤩🤩
