### ISSUE TITLE
Ask for help (about FlashFormulaEditor) 

### ISSUE THREAD

**Issue by G1xuan** [csarofeen/pytorch#1874]
### 🚀 The feature, motivation and pitch

Hi @zasdfgbnm ,sorry to disturb you!
I have some questions to ask you for help about FlashFormulaEditor(https://github.com/zasdfgbnm/FlashFormulaEditor)
When I read the README.md file I know FMEUnit what it means,"ax", "ay", "awidth" and "aheight" standing for "align x", "align y", "align width", and "align height" .
But,i want to know that how to get the aheight number for  unit.
For example,the FMESvgChar_A.as(https://github.com/zasdfgbnm/FlashFormulaEditor/blob/master/src/FMEUnits/FMESvgChars/FMESvgChar__A.as),this uint's aheight is "46.216",
how did you get this number?Just your feeling ? or you have same tool to get this number?
Because i want to add some new unit,so need to konw that~

Looking forward to your reply！

**Comment by zasdfgbnm** [comment]
That project is 10 years old and no longer maintained, and I no longer remember details about it. And this is not the correct place for asking for help for that project.

**Comment by G1xuan** [comment]
i am sorry about that~
Thanks~

> That project is 10 years old and no longer maintained, and I no longer remember details about it. And this is not the correct place for asking for help for that project.
