### ISSUE TITLE
[1.0 Requirement] Partitioning logic update

### ISSUE THREAD

**Issue by csarofeen** [csarofeen/pytorch#190]
Need to carefully update partitioning logic based on broadcast. Right now we can only fuse broadcasts that result in a single output shape. Consider the python multiple output tests:
```
    def test_broadcasting_multiple_output_shape(self):
        def t(x: torch.Tensor, y: torch.Tensor, z: torch.Tensor):
            o = x + 12
            o1 = o + y
            o2 = o + z
            oo = o1.sum() + o2.sum()
            return oo
        t_jit = torch.jit.script(t)
        x = torch.randn(32, 32, dtype=torch.float, device="cuda")
        y = torch.randn(2, 32, 32, dtype=torch.float, device="cuda")
        z = torch.randn(4, 32, 32, dtype=torch.float, device="cuda")
        jit_o = t_jit(x, y, z)
        jit_o = t_jit(x, y, z)
        o = t(x, y, z)
        self.assertEqual(o, jit_o)
        # Currently cannot fuse this
        self.assertGraphContains(t_jit.graph_for(x, y, z), FUSION_GROUP)

    def test_broadcasting_multiple_output(self):
        def t(x: torch.Tensor, y: torch.Tensor, z: torch.Tensor):
            o = x + 12
            o1 = o + y
            o2 = o + z
            oo = o1.sum() + o2.sum()
            return oo
        t_jit = torch.jit.script(t)
        x = torch.randn(32, 32, dtype=torch.float, device="cuda")
        y = torch.randn(4, 32, 32, dtype=torch.float, device="cuda")
        z = torch.randn(4, 32, 32, dtype=torch.float, device="cuda")
        jit_o = t_jit(x, y, z)
        jit_o = t_jit(x, y, z)
        o = t(x, y, z)
        self.assertEqual(o, jit_o)
        # Currently cannot fuse this
        self.assertGraphContains(t_jit.graph_for(x, y, z), FUSION_GROUP)
```

From the perspective of the fuser both of these tests result in outputs that we can't verify to be constant sizes. Therefore it is hard to create a generalized parallelization strategy. We need to carefully prevent fusion on this type of graph. Right now with our scheduling logic this will result (correctly so) in a computeAt error.

**Comment by jjsjann123** [comment]
Logging random ideas:

```
        def t(x: torch.Tensor, y: torch.Tensor, z: torch.Tensor):
            o = x + 12
            o1 = o + y
            o2 = o + z
```

Because y & z has no dependency, we won't be able to determine that o1 & o2 will be of the same size. Even if we do have the information somehow magically from profiling executor, if we want to incorporate that in graph partitioning logic, we will need to do shape inference in order to propagate the symbolic size. So it requires work.

In the mean time, if we try to simplify this by restricting graph partitioning, some ideas to do so are:

1. Preventing output intermediate tensors.
    When we merge nodes into fusion group, we can restrict the requirement to that the node can *NOT* have output(s) used by something other than the fusion. This will very effectively prevent any chances of multiple output with different shapes.
    But in training workflow, backward path would require intermediate tensors for gradient computation. this might be a no-go for that since nothing can be fused. (Note-to-myself, double check the graph output for training)

2. The other approach we can try is to restrict fusion via checking the size of output tensors and restrict the fusion to only happen when fusion produces outputs with consistent size (that is to say, a real output that is used by something out side of the fusion).
    This actually would not work to prevent a fusion graph from the second case, as when we look at the static output size, they do match.

3. IMO, the proper solution is to deduce the symbolic size for each output tensor in a consistent way. However, it has some major challenges:
    * This will be quite labor-intensive to handle outside of codegen, and it goes against our current direction of keeping shape inference inside codegen IR.
    * If we actually do this via codegen IR, the way we fuse graph right now (iterative approach that tries to fuse producer into consumer, where consumer is the fusion), means that we cannot grow the `Fusion` progressively (there's no mechanism to do that with our codegen api). We either need to re-do graph fusion (labor intensive and uncertainties), or pay extra overhead on the fusion pass.

**Comment by jjsjann123** [comment]
I'm currently leaning towards do approach 2), which is a lot more practical than approach 3). In cases where it fails to prevent a fusion that cannot be scheduled/lowered, we'll just use the fallback code path (that is to execute the graph unfused).

It is not ideal, but I'm hoping it will cope our targeted use cases just fine.

**Comment by jjsjann123** [comment]
Ended up doing option 3 without doing explicit shape inference. We currently rely on either profiling information or hope that we get lucky with shape inference.

Detailed implementation is commented inline in PR #280
