### ISSUE TITLE
[1.0 Requirement] Reductions on symbolic grid/block dimensions

### ISSUE THREAD

**Issue by csarofeen** [csarofeen/pytorch#195]
Right now the heuristics are written so that we have hard coded (constant) block and grid dimensions. We want the magic scheduler to leave these values as symbolic and return (for a given input) what these values should be.

**Comment by kevinstephano** [comment]
I think the general heuristic infrastructure is in place to allow for kernel caching with PR https://github.com/csarofeen/pytorch/pull/229.
