### ISSUE TITLE
Segfault when marking the same TensorView as output more than once

### ISSUE THREAD

**Issue by IvanYashchuk** [csarofeen/pytorch#1958]
### 🐛 Describe the bug

```python
import torch
from torch._C._nvfuser import Fusion, FusionDefinition

# Construct and Define Fusion
fusion = Fusion()

with FusionDefinition(fusion) as fd :
    t0 = fd.define_tensor(3)

    t1 = fd.ops.relu(t0)

    fd.add_output(t1)
    fd.add_output(t1)
    fd.add_output(t1)

fusion.print_ir()

# Execute Fusion
input1 = torch.ones(2, 4, 8, device='cuda')

# Kernel compilation should be cached for the 2nd iteration
# with input tensors of the same shape
for _ in range(1) :
    outputs = fusion.execute([input1,])

print(outputs)
```
```py
Inputs:
  T0_g[ iS0{i0}, iS1{i1}, iS2{i2} ], float
Outputs:
  T1_g[ iS3{i0}, iS4{i1}, iS5{i2} ], float
  T1_g[ iS3{i0}, iS4{i1}, iS5{i2} ], float
  T1_g[ iS3{i0}, iS4{i1}, iS5{i2} ], float

%kernel_math {
T1_g[ iS3{i0}, iS4{i1}, iS5{i2} ]
   = relu(T0_g[ iS0{i0}, iS1{i1}, iS2{i2} ]);
}

Segmentation fault (core dumped)
```

### Versions

Upstream master.

**Comment by csarofeen** [comment]
Do you expect this to happen in practice? Trying to understand how to prioritize this.

**Comment by naoyam** [comment]
What's the expected behavior? Can we just allow the first `addOutput` and ignore the rest? Or do we want to have the fusion with three outputs of the same tensor? The former should be trivial. The latter should also just need some simple extension.

**Comment by IvanYashchuk** [comment]
I think raising a meaningful error would be enough as a fix. Probably it's just adding a check for `isFusionOutput()` in `Fusion::addOutput`
https://github.com/csarofeen/pytorch/blob/b1bd32cc1b2ae7bbd44701477bddbcfa6642a9be/torch/csrc/jit/codegen/cuda/fusion.cpp#L208

**Comment by naoyam** [comment]
Actually, although I haven't thoroughly checked, it doesn't seem to fail at the Fusion IR level. Not saying I'm confident that it would work for more complex fusions, but at least for the error you saw, that's happening at the interface between Python and Fusion IR. 

```
Traceback (most recent call last):
  File "repro.py", line 24, in <module>
    outputs = fusion.execute([input1,])
RuntimeError: group_outputs.size() == group_runtime_outputs.size() INTERNAL ASSERT FAILED at "../torch/csrc/jit/codegen/cuda/kernel_cache.cpp":645, please report a bug to PyTorch. output size does not match
```

I'm not sure what's going on there, but maybe @kevinstephano or @jjsjann123 can chime in.

**Comment by IvanYashchuk** [comment]
Great, it's fixed in the `devel` branch. Most likely it was fixed with https://github.com/csarofeen/pytorch/pull/1914! There are no segfaults.
