### ISSUE TITLE
Code generator doesn't support reduction keepdim=true

### ISSUE THREAD

**Issue by csarofeen** [csarofeen/pytorch#205]
Reduction operations in pytorch make keep the reduced dimension as a size=1. We need to be able to support this use case in t he code generator.

**Comment by jjsjann123** [comment]
https://github.com/csarofeen/pytorch/blob/d9fc9515a858f047811021dc40035211ce657959/torch/csrc/jit/codegen/cuda/parser.cpp#L501-L503

note-to-myself: currently we are excluding reduction node with `keepdim==true` in partitioning. Need to remove that once support is added.

**Comment by naoyam** [comment]
Is this now closed with #424? @csarofeen @jjsjann123 @shmsong

**Comment by jjsjann123** [comment]
Not yet. You went ahead of me. I just started looking at the support in integration. I hope to do it along with `sum_to`. But it won't work for backward until we have scalar/list profiling support.
Anyway, I'll update the issue when my PR is up.
