### ISSUE TITLE
Add Factory Functions to Python Frontend

### ISSUE THREAD

**Issue by kevinstephano** [csarofeen/pytorch#2192]
### 🚀 The feature, motivation and pitch

Should include: `full, zeros, ones, arange, eye`.

There was a previous PR to an internal branch that exposed just `full`. #2057

**Comment by kevinstephano** [comment]
@rdspring1 just take your previous PR #2057 and get it to upstream.  We don't need the other operators as the prim is `full`.  

cc @mruberry

**Comment by rdspring1** [comment]
I created the upstream PR: https://github.com/pytorch/pytorch/pull/89230
