### ISSUE TITLE
Feature request: Warn register spill

### ISSUE THREAD

**Issue by naoyam** [csarofeen/pytorch#2313]
It would be quite useful if we could get warnings when register spill happened. For example:

```
PYTORCH_NVFUESR_ENABLE=warn_register_spill(10) ./build/bin/nvfuser_bench
```

Would give warnings if register spill happened with threshold of 10.

This should be relatively straightforward by looking at the ptxas verbose log string and doing some pattern matching.

**Comment by liqiangxl** [comment]
what's the meaning of ` threshold of 10`? I did a version without this threshold.

**Comment by naoyam** [comment]
I think it'd be useful to have some threshold of reporting. We probably don't care about spilling just a few bytes. I remember @zasdfgbnm added some code to allow an option to have a parameter.

**Comment by liqiangxl** [comment]
updated PR to add threshold.

**Comment by liqiangxl** [comment]
If I use` PYTORCH_NVFUSER_ENABLE=warn_register_spill(15)` , the bash will complain:
bash: syntax error near unexpected token (
It only works with `PYTORCH_NVFUSER_ENABLE="warn_register_spill(15)"` or `PYTORCH_NVFUSER_ENABLE='warn_register_spill(15)'`
--reason:
parentheses are used for grouping by the shell such that they are not communicated in any way to a command.
--if we want to allow ` PYTORCH_NVFUSER_ENABLE=warn_register_spill(15)`, need to refactor parameter parsing without using "()"
