### ISSUE TITLE
segfault with test_jit, even when non tests are run

### ISSUE THREAD

**Issue by jjsjann123** [csarofeen/pytorch#2329]
### 🐛 Describe the bug

The issue is patched in https://github.com/csarofeen/pytorch/pull/2328

It's repro'able even with `./build/bin/test_jit --gtest_filter="arbitrary_filter_that_matches_nothing"`

But the root cause of the segfault is unknown and we are concerned there's some real problems. Opening this issue to track it.

### Versions

Current top of tree:

```
commit bd6d82865ed8e638d33ee1cec78afcf6b6cc9f8f (origin/devel, origin/HEAD, devel)
Author: liqiangxl <116412316+liqiangxl@users.noreply.github.com>
Date:   Thu Jan 12 15:10:38 2023 -0500

    check welford input before trial translate to two-pass (#2325)
```

**Comment by naoyam** [comment]
Is there any specific condition to trigger this? (I don't see the error).

Maybe the configuration output of cmake would be helpful.

```
...
-- Configuring done
-- Generating done
-- Build files have been written to: /raid/nmaruyama/debug1/build
[1/4] Generating ATen declarations_yaml
````

**Comment by jjsjann123** [comment]
This was caught in our nightly containers.
Interesting that it didn't manifest in your setup. I wonder if it's clang or maybe debug build?

**Comment by naoyam** [comment]
Tried both Release and Debug with clang. Nothing seems broken. Will try gcc.

**Comment by naoyam** [comment]
Which compiler and version is used in the container?

**Comment by naoyam** [comment]
gcc 9.4.0 works fine for me

**Comment by jjsjann123** [comment]
hmm.... This is interesting.... Because I'm also using 9.4.0
```
root@c86fed8891ce:/opt/pytorch/pytorch# cc --version
cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@c86fed8891ce:/opt/pytorch/pytorch# c++ --version
c++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by jjsjann123** [comment]
In case you are curious, you can also pull `gitlab-master.nvidia.com:5005/dl/pytorch/update-scripts:jit-cuda11-latest`

**Comment by naoyam** [comment]
Thanks. BTW, are you seeing the error with `test_jit`, not with `nvfuser_tests`?

**Comment by jjsjann123** [comment]
> Thanks. BTW, are you seeing the error with `test_jit`, not with `nvfuser_tests`?

Sorry I missed the last message. But yes it's only with `test_jit` but not with `nvfuser_tests`.

**Comment by naoyam** [comment]
Jie and I tried the latest container again and didn't see any problem. We have no idea why the error happened. I'll revert the change and see if it shows up again.
