### ISSUE TITLE
[non-urgent] tune heuristics for inner persistent normalizaiton with hidden size <= 2048

### ISSUE THREAD

**Issue by liqiangxl** [csarofeen/pytorch#2331]
### 🚀 The feature, motivation and pitch

current heuristic was tuned with welford, didn't use warp reduciton. now since we are using two-pass with warp-reduciton, the best block size may be different.
![image](https://user-images.githubusercontent.com/116412316/212992374-f6a01c51-8628-441c-8d3c-7ef416e3fe54.png)

**Comment by naoyam** [comment]
Just adding one note that the perf gap compared to APEX doesn't look so bad even for the small problem sizes, so this shouldn't be an urgent issue to fix, but something we may want to revisit later.
