### ISSUE TITLE
Disjointness of segmented fusion may be invalidated due to welford translation

### ISSUE THREAD

**Issue by naoyam** [csarofeen/pytorch#2348]
Translation of welford exprs reuses existing exprs if found:

https://github.com/csarofeen/pytorch/blob/devel/third_party/nvfuser/csrc/fusion_segmenter.cpp#L2013-L2036

This however pulls in expressions that may belong to different segmented groups than the translated group. One place we do the translation is at the beginning of the segmentation where we have initial segmented groups, i.e., each group consists of a single expr. If the translation is done at this point, reusing would mean pulling in exprs to the welford group, but those exprs still exist in their original initial groups, so the disjointness gets invalidated.

To fix the issue, we should either just stop reusing or reinitialize segmented groups. 

I found this happened with some of the normalization tests such as `TestCudaFuser.test_norm_half`.

**Comment by naoyam** [comment]
Here's an example with `TestCudaFuser.test_norm_half`. Dumped all groups right after the welford translation:

```
g{8}
T8_l[ iS19{i10} ]
   = T2_g[ iS6{i10} ]
   * d28;
g{9}
T9_l[ bS20{1}, iS21{i10} ]
   = broadcast( T8_l[ iS19{i10} ] )
g{0}
T1_l[ iS3{i1}, iS4{i2}, iS5{i3} ]
   = __half2float(T0_g[ iS0{i1}, iS1{i2}, iS2{i3} ]);
g{25, 26, 37, 38, 39, 40}
T29_l[ iS63{i1}, iS64{i2}, rS65{i3} ]
   = reduction( T1_l[ iS3{i1}, iS4{i2}, iS5{i3} ], op = add, initial value = double(0), allreduce = false )
T4_l[ iS8{i1}, iS9{i2} ]
   = T29_l[ iS63{i1}, iS64{i2}, rS65{i3} ]
   / d103;
T20_l[ iS39{i1}, iS40{i2}, bS41{1} ]
   = broadcast( T4_l[ iS8{i1}, iS9{i2} ] )
T21_l[ iS42{i1}, iS43{i2}, iS44{i3} ]
   = T1_l[ iS3{i1}, iS4{i2}, iS5{i3} ]
   - T20_l[ iS39{i1}, iS40{i2}, bS41{1} ];
T30_l[ iS66{i1}, iS67{i2}, iS68{i3} ]
   = T21_l[ iS42{i1}, iS43{i2}, iS44{i3} ]
   * T21_l[ iS42{i1}, iS43{i2}, iS44{i3} ];
T5_l[ iS11{i1}, iS12{i2}, rS13{i3} ]
   = reduction( T30_l[ iS66{i1}, iS67{i2}, iS68{i3} ], op = add, initial value = double(0), allreduce = false )
g{7}
T7_l[ iS17{i1}, iS18{i2} ]
   = T4_l[ iS8{i1}, iS9{i2} ]
   * double(0.10000000149011612);
g{10}
T10_l[ iS22{i1}, iS23{i10} ]
   = T9_l[ bS20{1}, iS21{i10} ]
   + T7_l[ iS17{i1}, iS18{i2} ];
g{11}
T11_l[ rS24{i1}, iS25{i10} ]
   = reduction( T10_l[ iS22{i1}, iS23{i10} ], op = add, initial value = double(0), allreduce = false )
g{13}
T12_g[ iS26{i10} ]
   = T11_l[ rS24{i1}, iS25{i10} ]
   * d40;
g{19}
T15_l[ iS31{i11} ]
   = T3_g[ iS7{i11} ]
   * d28;
g{20}
T16_l[ bS32{1}, iS33{i11} ]
   = broadcast( T15_l[ iS31{i11} ] )
g{17}
T13_l[ iS27{i1}, iS28{i2} ]
   = T5_l[ iS11{i1}, iS12{i2}, rS13{i3} ]
   * d45;
g{18}
T14_l[ iS29{i1}, iS30{i2} ]
   = T13_l[ iS27{i1}, iS28{i2} ]
   * double(0.10000000149011612);
g{21}
T17_l[ iS34{i1}, iS35{i11} ]
   = T16_l[ bS32{1}, iS33{i11} ]
   + T14_l[ iS29{i1}, iS30{i2} ];
g{22}
T18_l[ rS36{i1}, iS37{i11} ]
   = reduction( T17_l[ iS34{i1}, iS35{i11} ], op = add, initial value = double(0), allreduce = false )
g{24}
T19_g[ iS38{i11} ]
   = T18_l[ rS36{i1}, iS37{i11} ]
   * d61;
g{25}
T20_l[ iS39{i1}, iS40{i2}, bS41{1} ]
   = broadcast( T4_l[ iS8{i1}, iS9{i2} ] )
g{26}
T21_l[ iS42{i1}, iS43{i2}, iS44{i3} ]
   = T1_l[ iS3{i1}, iS4{i2}, iS5{i3} ]
   - T20_l[ iS39{i1}, iS40{i2}, bS41{1} ];
g{28}
T22_l[ iS45{i1}, iS46{i2} ]
   = T5_l[ iS11{i1}, iS12{i2}, rS13{i3} ]
   * d70;
g{29}
T23_l[ iS47{i1}, iS48{i2} ]
   = T22_l[ iS45{i1}, iS46{i2} ]
   + double(9.9999997473787516e-06);
g{30}
T24_l[ iS49{i1}, iS50{i2} ]
   = rsqrtf(T23_l[ iS47{i1}, iS48{i2} ]);
g{31}
T25_l[ iS51{i1}, iS52{i2}, bS53{1} ]
   = broadcast( T24_l[ iS49{i1}, iS50{i2} ] )
g{32}
T26_l[ iS54{i1}, iS55{i2}, iS56{i3} ]
   = T21_l[ iS42{i1}, iS43{i2}, iS44{i3} ]
   * T25_l[ iS51{i1}, iS52{i2}, bS53{1} ];
g{33}
T27_l[ iS57{i1}, iS58{i2}, iS59{i3} ]
   = relu(T26_l[ iS54{i1}, iS55{i2}, iS56{i3} ]);
g{34}
T28_g[ iS60{i1}, iS61{i2}, iS62{i3} ]
   = __float2half(T27_l[ iS57{i1}, iS58{i2}, iS59{i3} ]);
g{}
g{}
g{}
```

The concerning group is:

```
g{25, 26, 37, 38, 39, 40}
T29_l[ iS63{i1}, iS64{i2}, rS65{i3} ]
   = reduction( T1_l[ iS3{i1}, iS4{i2}, iS5{i3} ], op = add, initial value = double(0), allreduce = false )
T4_l[ iS8{i1}, iS9{i2} ]
   = T29_l[ iS63{i1}, iS64{i2}, rS65{i3} ]
   / d103;
T20_l[ iS39{i1}, iS40{i2}, bS41{1} ]
   = broadcast( T4_l[ iS8{i1}, iS9{i2} ] )
T21_l[ iS42{i1}, iS43{i2}, iS44{i3} ]
   = T1_l[ iS3{i1}, iS4{i2}, iS5{i3} ]
   - T20_l[ iS39{i1}, iS40{i2}, bS41{1} ];
T30_l[ iS66{i1}, iS67{i2}, iS68{i3} ]
   = T21_l[ iS42{i1}, iS43{i2}, iS44{i3} ]
   * T21_l[ iS42{i1}, iS43{i2}, iS44{i3} ];
T5_l[ iS11{i1}, iS12{i2}, rS13{i3} ]
   = reduction( T30_l[ iS66{i1}, iS67{i2}, iS68{i3} ], op = add, initial value = double(0), allreduce = false )
```

This group contains expression newly added by `translateSingleWelford` as well as reused expressions such as `T1 - T20`, which also is included in:

```
g{26}
T21_l[ iS42{i1}, iS43{i2}, iS44{i3} ]
   = T1_l[ iS3{i1}, iS4{i2}, iS5{i3} ]
   - T20_l[ iS39{i1}, iS40{i2}, bS41{1} ];
```

**Comment by zasdfgbnm** [comment]
Are you saying that, different segments uses the same `Expr*`, so during lowering, if we do `expr->modifySomething()`, such as `expr->setPredicate`, then the lowering of one `Fusion` will mess up with the other? If we strictly follow the rule that `Expr` objects are never mutable, will we be OK with reusing expressions on different segments?

**Comment by naoyam** [comment]
I'm not sure what side effects there could be, but breaking the disjointness doesn't seem right.

I found this while working on #2344, where inserting of type casting is done based on the assumption of disjointness.

**Comment by csarofeen** [comment]
I think that was known and intended. I don't think the segmented groups have to be disjoint. I think we were expecting they in fact wouldn't be in some cases.

**Comment by naoyam** [comment]
Hmm, I didn't know that. Wonder if it still maintains the DAG property.

**Comment by csarofeen** [comment]
Does it actually take expressions from the segment or just recompute them?

**Comment by naoyam** [comment]
When a welford is translated, a single expression may be used in multiple groups without recomputation.

**Comment by naoyam** [comment]
It actually results in a cycle:

A group originally containing just a welford expr:

```
g{25, 26, 37, 38, 39, 40}
T29_l[ iS63{i1}, iS64{i2}, rS65{i3} ]
   = reduction( T1_l[ iS3{i1}, iS4{i2}, iS5{i3} ], op = add, initial value = double(0), allreduce = false )
T4_l[ iS8{i1}, iS9{i2} ]
   = T29_l[ iS63{i1}, iS64{i2}, rS65{i3} ]
   / d103;
T20_l[ iS39{i1}, iS40{i2}, bS41{1} ]
   = broadcast( T4_l[ iS8{i1}, iS9{i2} ] )
T21_l[ iS42{i1}, iS43{i2}, iS44{i3} ]
   = T1_l[ iS3{i1}, iS4{i2}, iS5{i3} ]
   - T20_l[ iS39{i1}, iS40{i2}, bS41{1} ];
T30_l[ iS66{i1}, iS67{i2}, iS68{i3} ]
   = T21_l[ iS42{i1}, iS43{i2}, iS44{i3} ]
   * T21_l[ iS42{i1}, iS43{i2}, iS44{i3} ];
T5_l[ iS11{i1}, iS12{i2}, rS13{i3} ]
   = reduction( T30_l[ iS66{i1}, iS67{i2}, iS68{i3} ], op = add, initial value = double(0), allreduce = false )
```

Here, the subtraction is taken from this group:

```
g{26}
T21_l[ iS42{i1}, iS43{i2}, iS44{i3} ]
   = T1_l[ iS3{i1}, iS4{i2}, iS5{i3} ]
   - T20_l[ iS39{i1}, iS40{i2}, bS41{1} ];
```

These two subtraction exprs are the same `Expr` object. 

Since `T20` is defined in the first group and is used in the second group, there is an edge from the first to second. Also, since `T21 is defined in the second and is used in the first, there's an edge from the second to the first, resulting in a cycle.

Is this expected? I thought the segmentation algorithm assumes DAGs.

**Comment by csarofeen** [comment]
I don't remember when we perform this translation. I didn't realize it's taking expressions from one group to another as it's translating. That does in fact seem wrong as yes we would require DAG on the overall segmentation for execution.

I recall this translation and reuse is important but I don't recall when we're trying to do this translation.

I was thinking of: https://github.com/csarofeen/pytorch/blob/devel/third_party/nvfuser/csrc/fusion_segmenter.cpp#L2668-L2671

Where we're taking in replicate expressions, which shouldn't ruin the overall DAG-ness of the resulting segmented graph.

**Comment by naoyam** [comment]
Hmm, that part of the code looks strange to me. `to_visit` are initialized to have `UnaryOp` exprs using fusion inputs, but then any `UnaryOp` is just visited with no action: 

```
    std::deque<Expr*> to_visit;
    for (auto inp : completeFusion()->inputs()) {
      if (std::all_of(inp->uses().begin(), inp->uses().end(), [](Expr* expr) {
            return expr->isA<UnaryOp>();
          })) {
        to_visit.insert(to_visit.end(), inp->uses().begin(), inp->uses().end());
      }
    }
```

```
     if (expr->isA<UnaryOp>() || expr->output(0)->isFusionOutput()) {
        continue;
      }
```

I may be missing something, but it seems that `excluded_inp_unary_exprs` and `forwarded_inputs` are always empty

**Comment by csarofeen** [comment]
https://github.com/csarofeen/pytorch/commit/8d3c95a959b8a684a0a3b63cf29ea07dd2eb3d82#diff-8be6009794181fb249d184ada1b1d66f6ed12c141cdb45d58b5b722b8fa243e2R2683

Hah, looks like a regression. This was a bad change in a big PR. Please try to revert and test perf before and after. I'm pretty sure this causes us to have extra passes on memory in one of the backward normalizations.

**Comment by naoyam** [comment]
Ah, I see. I'll fix it as well.

**Comment by naoyam** [comment]
@csarofeen I'll work on it as a separate PR. Tracked as issue #2351
