### ISSUE TITLE
SegmentCandidateFinder (fusion_segment.cpp) asserts on findSegments()

### ISSUE THREAD

**Issue by jjsjann123** [csarofeen/pytorch#2352]
### 🐛 Describe the bug

Original issue:
```
RuntimeError: h.has_value() INTERNAL ASSERT FAILED at "/opt/pytorch/pytorch/third_party/nvfuser/csrc/fusion_segmenter.cpp":2634, please report a bug to PyTorch. Can not find a scheduler to schedule fusion segment
```

SegmentCandidateFinder applies graph mutation in `finalize()` without query scheduler, which leads to segment groups that can't be scheduled later.

There is a hack in the handling of cast in segmenter. https://github.com/csarofeen/pytorch/blob/4c6465de0afbcaf8b9f251b1c119147207d7c120/third_party/nvfuser/csrc/fusion_segmenter.cpp#L759-L765

This unconditional mutation of segmented graph is the root cause of the segmenter failure with `gather` and `index_select`, which doesn't like arbitrarily inserted cast ops on the first tensor argument.

### Versions

TOT devel currently have this issue.
```
commit 4c6465de0afbcaf8b9f251b1c119147207d7c120 (csarofeen/devel)
Author: Kevin Stephano <kevin.stephano@gmail.com>
Date:   Fri Jan 20 14:32:48 2023 -0800

    Fix gather test to include removal of Fusion object usage. (#2349)

```

**Comment by jjsjann123** [comment]
The quick fix we can do is to double check with scheduler after graph mutation.

I'm wondering if there's a better place where we apply graph level optimization across the entire unsegmented fusion? cc'ing @naoyam

**Comment by naoyam** [comment]
I guess it may not be that simple. Since there are only a few cases that we shouldn't do the cast, excluding them from the cast would be a simpler fix. There's a related WIP PR that I'm working on (#2344), so let me take care of this.

Segmentation is highly overloaded as it doesn't just segment a fusion but also modifies the fusion with these cast ops as well as the welford translation. Guess it's time to refactor.

**Comment by jjsjann123** [comment]
Refactoring segmentation sounds like a good idea~

I'll leave the segmenter thing for you and just patch the scheduler + python API then.

**Comment by jjsjann123** [comment]
Oops. @naoyam just pointed out that I don't have the repro steps listed here.

The tests that were failing
```
test_nvfuser_correctness_gather_cuda_float16
test_nvfuser_correctness_index_select_cuda_float16
test_nvfuser_extremal_values_gather_cuda_float16
test_nvfuser_extremal_values_index_select_cuda_float16
```

Where you should be able to run them with `PYTORCH_TEST_WITH_SLOW=1 python ./test/test_jit_cuda_fuser.py -v -k [TEST_NAME_FROM_ABOVE]`

**Comment by jjsjann123** [comment]
This script should also give you the error (but I could have used better assert) :stuck_out_tongue: 

```
import torch
from nvfuser._C import FusionDefinition, DataType

def nvfuser_fusion(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(1, dtype=DataType.Half)
    T1 = fd.define_tensor(1, dtype=DataType.Int)
    T2 = fd.ops.cast(T0, DataType.Float)
    T3 = fd.ops.index_select(T2, T1, 0)
    T4 = fd.ops.cast(T3, DataType.Half)
    fd.add_output(T4)

inputs = [
    torch.randn(8, device='cuda').to(dtype=torch.half),
    torch.randint(0, 8, (8,), device='cuda').to(dtype=torch.long),
]

fd = FusionDefinition()
with fd:
    nvfuser_fusion(fd)

oo = torch.index_select(inputs[0], 0, inputs[1])
print(oo.shape)

o = fd.execute(inputs)
print(fd.__repr__())
for _ in range(5) :
    o = fd.execute(inputs)


print(o)
print(o[0].shape)
```
