### ISSUE TITLE
Performing an operation on a tensor defined using `ndims` that was then broadcast will error

### ISSUE THREAD

**Issue by mruberry** [csarofeen/pytorch#2359]
```
fs = Fusion()
with FusionDefinition(fs) as fd:
    nv_a = fd.define_tensor(ndims=2, dtype=DataType.Float)
    nv_b = fd.define_tensor(ndims=2, dtype=DataType.Float)

    c = fd.ops.broadcast_in_dim(nv_a, (2, 2), (0, 1))
    result = fd.ops.add(nv_b, c)

    fd.add_output(result)

a = make_tensor((2, 1), device='cuda', dtype=torch.float32)
b = make_tensor((2, 2), device='cuda', dtype=torch.float32)
nv_result = fs.execute([a, b])[0]
print(nv_result)
: RuntimeError: Attempting to bind T0.size[1] to 2 but it's already set to 1
```

This works:

```
a = make_tensor((2, 1), device='cuda', dtype=torch.float32)
b = make_tensor((2, 2), device='cuda', dtype=torch.float32)

fs = Fusion()
with FusionDefinition(fs) as fd:
    nv_a = fd.define_tensor(sizes=a.shape, strides=a.stride(), dtype=DataType.Float)
    nv_b = fd.define_tensor(ndims=2, dtype=DataType.Float)

    c = fd.ops.broadcast_in_dim(nv_a, (2, 2), (0, 1))
    result = fd.ops.add(nv_b, c)

    fd.add_output(result)


nv_result = fs.execute([a, b])[0]
print(nv_result)
: tensor([[-6.2342,  6.0266],
           [-2.2326,  5.1130]], device='cuda:0')
```

**Comment by jjsjann123** [comment]
```
    nv_a = fd.define_tensor(ndims=2, dtype=DataType.Float)
    c = fd.ops.broadcast_in_dim(nv_a, (2, 2), (0, 1))
```

Should we checking tensor dimensions in `broadcast_in_dim` and throw a warning there? @kevinstephano 

e.g. nv_a definition gives us this vvv, which is a no-op when we call `broadcast_in_dim`. I think it's worth throw a warning, when user try to expand/broadcast on an iterative dimension `iS1`.
```
Inputs:
  T0_g[ iS0{i0}, iS1{i1} ], float
```

**Comment by kevinstephano** [comment]
I think the problem exists not with `broadcast_in_dim` but the fact that the definition is not valid for broadcasts as it was defined to believe it would not see a broadcast as we rely on broadcasts being marked explicitly in inputs.  Perhaps, the error that should be created is that the given inputs should trip an error earlier.

**Comment by jjsjann123** [comment]
I agree with you. In the example above, we know the error was in the tensor definition.

But if we just look at the part where fusion is defined vvv
```
with FusionDefinition(fs) as fd:
    nv_a = fd.define_tensor(ndims=2, dtype=DataType.Float)  # we have no clue where the real input tensor is / would be, so we can't really error out here.
    nv_b = fd.define_tensor(ndims=2, dtype=DataType.Float)

    c = fd.ops.broadcast_in_dim(nv_a, (2, 2), (0, 1))  # This is where the inconsistency happens, at least at this point we know that the broadcast_in_dim called on nv_a is not valid and this is likely where we can throw a warning?
    result = fd.ops.add(nv_b, c)

    fd.add_output(result)
```

**Comment by mruberry** [comment]
From a user perspective, however, I don't understand what's "invalid" about `nv_a` in the above example. Doesn't `define_tensor` just describe some the properties of the input? And in this case I believe they're accurately described, right?

**Comment by jjsjann123** [comment]
> From a user perspective, however, I don't understand what's "invalid" about `nv_a` in the above example. Doesn't `define_tensor` just describe some the properties of the input? And in this case I believe they're accurately described, right?

Yeah this part here is very confusing to an user. vvv

`a = make_tensor((2, 1), device='cuda', dtype=torch.float32)` vs `nv_a = fd.define_tensor(ndims=2, dtype=DataType.Float)`.

since we specialize on `size-1` being a broadcasted dimension, when creating a `TensorView` for the given tensor with shape `(2, 1)`. You need to specify that the inner dimension is broadcast when calling `define_tensor`.

The `invalid` part comes when you have
```
nv_a = fd.define_tensor(ndims=2, dtype=DataType.Float)
c = fd.ops.broadcast_in_dim(nv_a, (2, 2), (0, 1))
```
so you are expanding a non-broadcast dimension, which is not a legit definition. Currently I think broadcast_in_dim just ignores it and I think this is the part where we should either assert or just throw a VERY LOUD warning.

**Comment by jjsjann123** [comment]
I think we should also discuss the API for tensor definition....

Having explicit control with `fd.define_tensor` sounds all good (especially for debugging). But we are also offloading the responsibility to user to understand the dynamic shape mechanism that nvfuser uses... which could be too much....

Granted that if we want the cache system between the user & nvfuser to work in coordination, this part is needed. But should we also provide a simple wrapper for user to create nvfuser tensor from an existing pytorch tensor, so we can hide all these complexities and provide a simpler API for people to pick up. Something like we did in cpp world (https://github.com/csarofeen/pytorch/blob/2b433680c25c3af1653c0f6f12f972d333f638ba/third_party/nvfuser/csrc/tensor_view.cpp#L41-L43)

**Comment by kevinstephano** [comment]
We removed the API that tripped this error and replaced it with a new one called `from_pytorch`.  The PR is available in our Dev Fork, only, at this point.
