### ISSUE TITLE
calling complex rsqrt will throw a runtime error due to compilation failure

### ISSUE THREAD

**Issue by mruberry** [csarofeen/pytorch#2367]
```
 __global__ void kernel62(Tensor<std::complex<float>, 0> T0, Tensor<std::complex<float>, 0> T2) {
E     std::complex<float> T1[1];
E     T1[0]
E        = rsqrt(T0[0]);
E     T2[0]
E        = T1[0];
E   }
E   }
E   
E   CUDA NVRTC compile error: __tmp_kernel62.cu(7898): error: more than one instance of overloaded function "rsqrt" matches the argument list:
E               function "rsqrt(double)"
E   __nv_nvrtc_builtin_header.h(166837): here
E               function "rsqrt(float)"
E   __nv_nvrtc_builtin_header.h(168105): here
E               argument types are: (CudaCodeGen::std::complex<float>)
```

rsqrt could be enabled for complex inputs, or a nicer error could be thrown when the fusion is defined

**Comment by jjsjann123** [comment]
Looks like we don't have rsqrt for complex in pytorch/llvm... 
https://github.com/csarofeen/pytorch/issues/2360#issuecomment-1404026251

We'll just need to add an entry for `complex<double>` as well as `complex<float>` in `runtime/helpers.cu`

cc'ing @zasdfgbnm

**Comment by mruberry** [comment]
This also occurs with operations like `sum`. Hitting an error in compilation is not a great user experience, and it'd be nice if an error occurred while defining the fusion when an operator is called with an argument of a datatype it doesn't support

https://github.com/csarofeen/pytorch/issues/2369
