### ISSUE TITLE
Some datatype conversions are not supported

### ISSUE THREAD

**Issue by mruberry** [csarofeen/pytorch#2370]
Like converting bfloat16 to double

**Comment by zasdfgbnm** [comment]
I feel surprised because we have this test:
https://github.com/csarofeen/pytorch/blob/f139de1cecdb78b78064f593001630cc36704afd/third_party/nvfuser/test/test_gpu3.cpp#L6526-L6582
And I believe that this test is exhaustive. You are probably using a pre-Ampere device?

**Comment by mruberry** [comment]
I'm on an Ampere device. Maybe my version of nvFuser is old?

**Comment by zasdfgbnm** [comment]
> I'm on an Ampere device. Maybe my version of nvFuser is old?

These castings are added in https://github.com/csarofeen/pytorch/pull/2084, is your branch older than that?

**Comment by mruberry** [comment]
> > I'm on an Ampere device. Maybe my version of nvFuser is old?
> 
> These castings are added in #2084, is your branch older than that?

I just updated PyTorch and I still see some casts, like int64 to bfloat, failing.

**Comment by zasdfgbnm** [comment]
I think the upstream nvfuser is pretty old. In this file, https://github.com/pytorch/pytorch/blob/master/third_party/nvfuser/test/test_gpu3.cpp, there is no `FusionCastings_CUDA`

**Comment by mruberry** [comment]
Confirmed this is fixed on devel
