### ISSUE TITLE
Expose Normal and Uniform nvFuser functions through the Python Frontend

### ISSUE THREAD

**Issue by kevinstephano** [csarofeen/pytorch#2386]
### 🚀 The feature, motivation and pitch

Expose normal and uniform randomization functions to python frontend.  Some of this might already exist.  Would just need to verify in that case.

**Comment by jjsjann123** [comment]
We don't have those in python APIs yet. I'm adding them. Looking pretty straightforward~

**Comment by jjsjann123** [comment]
I'm closing this one as uniform & norm API is merged now.
