### ISSUE TITLE
Needs clarification on what ParallelType::Unroll do

### ISSUE THREAD

**Issue by FDecaYed** [csarofeen/pytorch#265]
## 📚 Documentation

Currently the doc states that unroll doesn't really unroll the loop, but sepate the outer loop into 2 parts, so in the bulk part predicate can be moved ouside inner loop. @csarofeen could you clarify why we are doing this now and what is the goal?

Even adding pragma unroll later, my understanding is we will still be relying on compiler for the most important [pipelining](https://en.wikipedia.org/wiki/Software_pipelining) optimization we need. @jjsjann123 and I tested this and it seems ptxas re-ordering well on the case of casting on load/store. But I think this depends on what's inside the loop.

It is more confusing on reduction case. Since there is dependency between loop interations, intuitively I feel unrolling means create multiple local partial result so that dependency is removed and loop can be fully unrolled.
As shown in https://github.com/csarofeen/pytorch/issues/176 and https://github.com/csarofeen/pytorch/issues/264, computeAt intermediate is stored in array but there is only a single result to do reduction on.

**Comment by csarofeen** [comment]
Sorry for not responding to this originally. Closing as stale. Unrolling behavior has evolved, but I believe the approach we are taking is roughly in line with what you're suggesting. We do still rely on the compiler to do reasonable pipelining and haven't seen cases where it fails do to it as needed.
