### ISSUE TITLE
Replace the type tag with runtime type information

### ISSUE THREAD

**Issue by naoyam** [csarofeen/pytorch#268]
We have code like this:

```
Val *val = ...;
if (val->getValType() == ValType::TensorView) {
  // do something when val is TensorView
}
```

This can be rewritten as:
```
Val *val = ...;
if (dynamic_cast<const TensorView*>(val)) {
  // do something when val is TensorView
}
```

An assumption is that each sub class of `Val` has its own unique `ValType` value. This seems to be the case, so `dynamic_cast` should be equivalent to the tag-based type checking. If we want to have multiple different classes but with the same `ValType` value for some reason, `dynamic_cast` wont' work.

**Comment by naoyam** [comment]
The assumption is actually not correct. `ValType` of `Bool`, `Floa`, and `Int` are all `ValType::Scalar`.

**Comment by csarofeen** [comment]
We do use both, and will continue to do so.
