### ISSUE TITLE
computeAt inline everything fails python random topology test

### ISSUE THREAD

**Issue by jjsjann123** [csarofeen/pytorch#299]
## 🐛 Bug

Using a naive schedule of

0. merge all outputs axes
1. split axes for unroll & TID.x binding
2. `input->computeAt(output, -1)`
3. bind output axes

actually fails a python random topology test (we only use PW operations fusions there). This very surprising to me and was exposed when I was investigating #230.

Opening an issue as it's taking me longer than expected to figure it out.

**Comment by jjsjann123** [comment]
Turns out the failure is legit numerical issues. If I disable multiplication in topo test, everything runs fine.
The problem is with FMA, our naive scheduler doesn't give the *right* fused kernel, so it avoids the numerical issue that way.

I'm leaving this one open for now. I'll disable multiplication in topo test just to make our life easier, topo test should focus on handling of random topology only!

**Comment by jjsjann123** [comment]
Just to clarify in case others are reading.

FMA is good in terms of higher accuracy. The only problem is that we are comparing with native eager execution, which doesn't use FMA (because it's two operation). So numerical issue doesn't suggest accuracy drop, it merely indicates that our result drifted from the eager output further.

**Comment by csarofeen** [comment]
I think this may be fixed, but without repro can't test.

**Comment by jjsjann123** [comment]
~IIRC, we disabled fast math so the numerical issues are no longer relevant. closing.~
I was dumb, we are still using fma so this is still relevant. But again, it's only numerical issue so there's not much to be done. closing.
