### ISSUE TITLE
1.0 perf improvements

### ISSUE THREAD

**Issue by csarofeen** [csarofeen/pytorch#308]
A few areas we need to make rapid progress identified by myself and Jie reviewing just the LSTM benchmark in PyTorch.
CC @jjsjann123 @naoyam 

- [x] Caching itself on size + stride information of inputs
- [x] Expression evaluator inference time (150 us)
- [x] Fixes on integration code (remove redundant IR processing on hot path)
- [x] Rework pointwise scheduler (unrolling vs inlining, depends on number of input tensors)
- [x] Rework expression order to be breadth first
- [x] Rework input and outputs to use cache_read/write
- [x] Rework Unrolling (predicate generation on unrolling is verbose, make sure it works with unrolling factor of 1)

**Comment by naoyam** [comment]
I created a very simple test for breadth-first ordering. See https://github.com/csarofeen/pytorch/blob/breadth-first/test/cpp/jit/test_gpu.cpp#L5978.

The generated code looks like this:

```
__global__ void CUDAGeneratedKernel(Tensor<float, 2> T0, Tensor<float, 2> T3, Tensor<float, 2> T2, Tensor<float, 2> T5, Tensor<float, 2> T6){
  for(size_t i1 = 0; i1 < T0.size[0]; ++i1 ) {
    for(size_t i5 = 0; i5 < ( ceilDiv(T0.size[1], 128) ); ++i5 ) {
      for(size_t i7 = 0; i7 < 128; ++i7 ) {
        float T4[1];
        float T1[1];
        if ( ( ( ( i5 * 128 ) + i7 ) < T0.size[1] ) ) {
          T1[ 0 ]
             = T0[ ( i1 * T0.stride[0] ) + ( ( ( i5 * 128 ) + i7 ) * T0.stride[1] ) ]
             + float(1);
        }
        if ( ( ( ( i5 * 128 ) + i7 ) < T0.size[1] ) ) {
          T2[ ( i1 * T2.stride[0] ) + ( ( i5 * 128 ) + i7 ) ]
             = T1[ 0 ]
             + float(2);
        }
        if ( ( ( ( i5 * 128 ) + i7 ) < T3.size[1] ) ) {
          T4[ 0 ]
             = T3[ ( i1 * T3.stride[0] ) + ( ( ( i5 * 128 ) + i7 ) * T3.stride[1] ) ]
             + float(1);
        }
        if ( ( ( ( i5 * 128 ) + i7 ) < T3.size[1] ) ) {
          T5[ ( i1 * T5.stride[0] ) + ( ( i5 * 128 ) + i7 ) ]
             = T4[ 0 ]
             + float(2);
        }
        if ( ( ( ( i5 * 128 ) + i7 ) < T0.size[1] ) ) {
          T6[ ( i1 * T6.stride[0] ) + ( ( i5 * 128 ) + i7 ) ]
             = T2[ ( i1 * T2.stride[0] ) + ( ( i5 * 128 ) + i7 ) ]
             + T5[ ( i1 * T5.stride[0] ) + ( ( i5 * 128 ) + i7 ) ];
        }
      }
    }
  }
}
```

I'm going to try to reorder `T1`, `T2`, `T4` and `T5`. Specifically, we want the inner-most loop body to look like as follows:

```
        float T4[1];
        float T1[1];
        if ( ( ( ( i5 * 128 ) + i7 ) < T0.size[1] ) ) {
          T1[ 0 ]
             = T0[ ( i1 * T0.stride[0] ) + ( ( ( i5 * 128 ) + i7 ) * T0.stride[1] ) ]
             + float(1);
        }
        if ( ( ( ( i5 * 128 ) + i7 ) < T3.size[1] ) ) {
          T4[ 0 ]
             = T3[ ( i1 * T3.stride[0] ) + ( ( ( i5 * 128 ) + i7 ) * T3.stride[1] ) ]
             + float(1);
        }
        if ( ( ( ( i5 * 128 ) + i7 ) < T0.size[1] ) ) {
          T2[ ( i1 * T2.stride[0] ) + ( ( i5 * 128 ) + i7 ) ]
             = T1[ 0 ]
             + float(2);
        }
        if ( ( ( ( i5 * 128 ) + i7 ) < T3.size[1] ) ) {
          T5[ ( i1 * T5.stride[0] ) + ( ( i5 * 128 ) + i7 ) ]
             = T4[ 0 ]
             + float(2);
        }
        if ( ( ( ( i5 * 128 ) + i7 ) < T0.size[1] ) ) {
          T6[ ( i1 * T6.stride[0] ) + ( ( i5 * 128 ) + i7 ) ]
             = T2[ ( i1 * T2.stride[0] ) + ( ( i5 * 128 ) + i7 ) ]
             + T5[ ( i1 * T5.stride[0] ) + ( ( i5 * 128 ) + i7 ) ];
        }
```

**Comment by jjsjann123** [comment]
Putting myself on caching of size+stride.

**Comment by naoyam** [comment]
> I created a very simple test for breadth-first ordering. See https://github.com/csarofeen/pytorch/blob/breadth-first/test/cpp/jit/test_gpu.cpp#L5978.
> 
> The generated code looks like this:
> 
> ```
> __global__ void CUDAGeneratedKernel(Tensor<float, 2> T0, Tensor<float, 2> T3, Tensor<float, 2> T2, Tensor<float, 2> T5, Tensor<float, 2> T6){
>   for(size_t i1 = 0; i1 < T0.size[0]; ++i1 ) {
>     for(size_t i5 = 0; i5 < ( ceilDiv(T0.size[1], 128) ); ++i5 ) {
>       for(size_t i7 = 0; i7 < 128; ++i7 ) {
>         float T4[1];
>         float T1[1];
>         if ( ( ( ( i5 * 128 ) + i7 ) < T0.size[1] ) ) {
>           T1[ 0 ]
>              = T0[ ( i1 * T0.stride[0] ) + ( ( ( i5 * 128 ) + i7 ) * T0.stride[1] ) ]
>              + float(1);
>         }
>         if ( ( ( ( i5 * 128 ) + i7 ) < T0.size[1] ) ) {
>           T2[ ( i1 * T2.stride[0] ) + ( ( i5 * 128 ) + i7 ) ]
>              = T1[ 0 ]
>              + float(2);
>         }
>         if ( ( ( ( i5 * 128 ) + i7 ) < T3.size[1] ) ) {
>           T4[ 0 ]
>              = T3[ ( i1 * T3.stride[0] ) + ( ( ( i5 * 128 ) + i7 ) * T3.stride[1] ) ]
>              + float(1);
>         }
>         if ( ( ( ( i5 * 128 ) + i7 ) < T3.size[1] ) ) {
>           T5[ ( i1 * T5.stride[0] ) + ( ( i5 * 128 ) + i7 ) ]
>              = T4[ 0 ]
>              + float(2);
>         }
>         if ( ( ( ( i5 * 128 ) + i7 ) < T0.size[1] ) ) {
>           T6[ ( i1 * T6.stride[0] ) + ( ( i5 * 128 ) + i7 ) ]
>              = T2[ ( i1 * T2.stride[0] ) + ( ( i5 * 128 ) + i7 ) ]
>              + T5[ ( i1 * T5.stride[0] ) + ( ( i5 * 128 ) + i7 ) ];
>         }
>       }
>     }
>   }
> }
> ```
> 
> I'm going to try to reorder `T1`, `T2`, `T4` and `T5`. Specifically, we want the inner-most loop body to look like as follows:
> 
> ```
>         float T4[1];
>         float T1[1];
>         if ( ( ( ( i5 * 128 ) + i7 ) < T0.size[1] ) ) {
>           T1[ 0 ]
>              = T0[ ( i1 * T0.stride[0] ) + ( ( ( i5 * 128 ) + i7 ) * T0.stride[1] ) ]
>              + float(1);
>         }
>         if ( ( ( ( i5 * 128 ) + i7 ) < T3.size[1] ) ) {
>           T4[ 0 ]
>              = T3[ ( i1 * T3.stride[0] ) + ( ( ( i5 * 128 ) + i7 ) * T3.stride[1] ) ]
>              + float(1);
>         }
>         if ( ( ( ( i5 * 128 ) + i7 ) < T0.size[1] ) ) {
>           T2[ ( i1 * T2.stride[0] ) + ( ( i5 * 128 ) + i7 ) ]
>              = T1[ 0 ]
>              + float(2);
>         }
>         if ( ( ( ( i5 * 128 ) + i7 ) < T3.size[1] ) ) {
>           T5[ ( i1 * T5.stride[0] ) + ( ( i5 * 128 ) + i7 ) ]
>              = T4[ 0 ]
>              + float(2);
>         }
>         if ( ( ( ( i5 * 128 ) + i7 ) < T0.size[1] ) ) {
>           T6[ ( i1 * T6.stride[0] ) + ( ( i5 * 128 ) + i7 ) ]
>              = T2[ ( i1 * T2.stride[0] ) + ( ( i5 * 128 ) + i7 ) ]
>              + T5[ ( i1 * T5.stride[0] ) + ( ( i5 * 128 ) + i7 ) ];
>         }
> ```

This is now working in the breadth-first branch (https://github.com/csarofeen/pytorch/tree/breadth-first), though I still need to do more extensive testing and code cleanup.

**Comment by csarofeen** [comment]
I think this is all completed, closing as stale.
