### ISSUE TITLE
Lowering failed to generate valid code

### ISSUE THREAD

**Issue by naoyam** [csarofeen/pytorch#319]
While working on an example in the Codegen Manual ("interesting case"), I encountered a problem that seems to be related to lowering. Here's a snippet. For full code, see `FusionComputeAtBCastReduction` in https://github.com/naoyam/pytorch/blob/compute-at-bugs/test/cpp/jit/test_gpu.cpp.

```
int x = 100;
  int y = 200;
  int z = 300;
  auto tv0 = makeConcreteTensor({x, y});
  fusion.addInput(tv0);

  auto tv1 = add(tv0, new Float(1));

  auto tv2 = sum(tv1, {0});
  auto tv3 = broadcast(tv2, {false, true});
  //auto tv4 = makeDummyTensor(2);
  auto tv4 = makeConcreteTensor({y, x});
  fusion.addInput(tv4);
  auto tv5 = add(tv3, tv4);
  fusion.addOutput(tv5);

  // broadcast then reduce
  auto tv6 = broadcast(tv1, {true, false, false});
  auto tv7 = sum(tv6, {-1});
  //auto tv8 = makeDummyTensor(2);
  auto tv8 = makeConcreteTensor({z, x});
  fusion.addInput(tv8);
  auto tv9 = mul(tv7, tv8);
  fusion.addOutput(tv9);

  tv0->computeAt(tv5, 1);
```

The generated code is:

```
__global__ void kernel1(Tensor<float, 2> T0, Tensor<float, 2> T4, Tensor<float, 2> T8, Tensor<float, 2> T5, Tensor<float, 2> T9){
  float T7[100];
  for(size_t i200 = 0; i200 < 100; ++i200 ) {
    T7[ i200 ]
       = float(0);
  }
  for(size_t i184 = 0; i184 < 300; ++i184 ) {
    for(size_t i187 = 0; i187 < 100; ++i187 ) {
      T5[ ( i184 * T5.stride[0] ) + i187 ]
         = T3[ 0 ]
         + T4[ ( i184 * T4.stride[0] ) + ( i187 * T4.stride[1] ) ];
    }
    for(size_t i190 = 0; i190 < 200; ++i190 ) {
      float T6[100];
      for(size_t i196 = 0; i196 < 100; ++i196 ) {
        T6[ i196 ]
           = T1[ ( i196 * 200 ) + i190 ];
      }
      for(size_t i198 = 0; i198 < 100; ++i198 ) {
        T7[ i198 ]
           = T7[ i198 ]
           + T6[ i198 ];
      }
    }
  }
  for(size_t i201 = 0; i201 < 300; ++i201 ) {
    float T3[1];
    float T2[1];
    T2[ 0 ]
       = float(0);
    float T1[100];
    for(size_t i202 = 0; i202 < 100; ++i202 ) {
      T1[ i202 ]
         = T0[ ( i202 * T0.stride[0] ) + ( i201 * T0.stride[1] ) ]
         + float(1);
    }
    for(size_t i203 = 0; i203 < 100; ++i203 ) {
      T2[ 0 ]
         = T2[ 0 ]
         + T1[ i203 ];
    }
    T3[ 0 ]
       = T2[ 0 ];
    for(size_t i209 = 0; i209 < 100; ++i209 ) {
      T9[ ( i201 * T9.stride[0] ) + i209 ]
         = T7[ i209 ]
         * T8[ ( i201 * T8.stride[0] ) + ( i209 * T8.stride[1] ) ];
    }
  }
}
```

The problem is that `T1` and `T3` are used before defined. 

The example test uses concrete tensors as inputs just for avoiding allocation of dynamic temporary buffers. The same problem seems to happen with normal tensors.

**Comment by naoyam** [comment]
This is a very difficult problem and is likely to have multiple root causes, some of which hopefully are captured in #322, #323, #328, #329.

**Comment by naoyam** [comment]
Just noting that I tried this with the latest devel, and it still failed. My guess is that this is due to our logic of loop-nest generation.

**Comment by csarofeen** [comment]
@naoyam please check if this is still an issue or if we've fixed it at some point.

**Comment by naoyam** [comment]
@csarofeen With the latest devel branch, we get at `tv0->computeAt(tv5, 1)`:

```
C++ exception with description "producer_compute_at_pos <= max_producer_compute_at_posINTERNAL ASSERT FAILED at "../torch/csrc/jit/codegen/cuda/compute_at.cpp":532, please report a bug to PyTorch. Invalid compute at position detected in compute at when trying to replay consumer: T9_g[ iS20{300}, iS21{100} ] as producer: T7_l[ rS17{200}, bS15{1}, iS16{100} ] produce_pos( 1) tried to do this at position: 1 but max position that's allowed is 0
Exception raised from forwardComputeAt_impl at ../torch/csrc/jit/codegen/cuda/compute_at.cpp:532 (most recent call first):
```

And I think this is the right behavior. In this synthetic fusion, the first axis of `tv5` matches with the second axis of  `tv0` and `tv1`, so `tv0->computeAt(tv5, 1)` moves the second axis of `tv1` to the first position. That in turn means the third axis of `tv6`, which corresponds to the second axis of `tv1`, is moved to the first position. Since the corresponding axis of `tv7` is a reduction axis, the maximum CA position of `tv7` becomes 0, and this results in a failure when doing `replayCasP` with `tv7` and `tv9`. The overall logic does make sense, so it does require some effort to understand why, the failure is the correct behavior.
