### ISSUE TITLE
Producer-Consumer axis mapping can be wrong

### ISSUE THREAD

**Issue by csarofeen** [csarofeen/pytorch#328]
The code to line axes up between a producer and a consumer is located at:
https://github.com/csarofeen/pytorch/blob/20_8_18_devel/torch/csrc/jit/codegen/cuda/ir_nodes.cpp#L889-L910

This code assumes that we start at the left most position and try to match axes as we iterate to the right of domains. However, this introduces an assumption on the ordering of broadcast axes. If we have the fusion:
```.cpp
    int x = 2, y = 3, z = 4;
    auto tv0 = makeConcreteTensor({z});
    auto tv1 = broadcast(tv0, {true, false});
    auto tv2 = broadcast(tv1, {false, true, false});
    auto tv3 = makeConcreteTensor({x, y, z});
    auto tv4 = mul(tv2, tv3);
    //     [ 2,  3,  4]
    // tv0 [        i2]
    // tv1 [b0,     i2]
    // tv2 [b0, b1, i2]
    // tv3 [i0, i1, i2]
    // tv4 [i0, i1, i2]
```
Axis mapping from `tv1` -> `tv2` will line up appropriately on `b0` with no mapping on `b1`. However if we flip the broadcast order on tv1/tv2 as:
```.cpp
    int x = 2, y = 3, z = 4;
    auto tv0 = makeConcreteTensor({z});
    auto tv1 = broadcast(tv0, {true, false});
    auto tv2 = broadcast(tv1, {true, false, false});
    auto tv3 = makeConcreteTensor({x, y, z});
    auto tv4 = mul(tv2, tv3);
    //     [ 2,  3,  4]
    // tv0 [        i2]
    // tv1 [    b1, i2]
    // tv2 [b0, b1, i2]
    // tv3 [i0, i1, i2]
    // tv4 [i0, i1, i2]
```
Now `tv1[b1]` will be mapped to `tv2[b0]` because of the implicit ordering assumption. Likely we should either:

1. Generate the root domain axes mapping when we construct expressions and store them in the fusion
2. Generate root domain axes by explicitly looking at the expressions that generate TVs

I'm uncertain how big of an issue this is today as indexing is failing on the above cases, so we may have bugs to deal with before we can handle this one.

**Comment by naoyam** [comment]
Fixed by #423.
