### ISSUE TITLE
Enable parameter cache for `FusionExecutor`

### ISSUE THREAD

**Issue by jjsjann123** [csarofeen/pytorch#335]
## 🚀 Feature

We should duplicate the module to generate the key used by cache lookup table from input set to unique id in `FusionExecutor::runFusion`. Where same logic would apply to the input sets and generate a unique id that allows the launch short-cut without feeding a unique id from `GraphCache`

## Motivation

In currently implementation, a unique id is generated by `GraphCache` for each input set, which is sufficient to ensure the "universal uniqueness" for an id shared among all inputs to a given graph, when a kernel is executed in integration.

However, the "universal uniqueness" of a given id could be hard to achieve when we have a duplicated module, given the way it is generated. New id is given to a input set on the sequence/order of an input set is seen by the module.

Nevertheless, we are exposing the encoding module only to facilitates writing cpp tests. This means that, at least for now, we could simplify the implementation without worrying about the universal uniqueness of a given id across the module in `GraphCache` and `FusionExecutor`. That means we can just duplicate it as-is without any modification.

**Comment by csarofeen** [comment]
I'm not sure I follow, is this still relevant @jjsjann123?

**Comment by jjsjann123** [comment]
This is already handled when we plumb the cache id down to our hierarchical cache. closing.
