### ISSUE TITLE
Return TensorView* from arith ops when possible

### ISSUE THREAD

**Issue by csarofeen** [csarofeen/pytorch#36]
It's really annoying to work with Arith and have it always return a `Val*` when we frequently use `TensorView*` as args. We should overload these operators to return a `TensorView*` when there is one in the inputs.

We should then modify our tests which frequently have syntax like:
```  TensorView* tv1 = static_cast<TensorView*>(add(tv0, new Float(2.0)));
  TensorView* tv2 = static_cast<TensorView*>(add(tv1, new Float(3.0)));
```
to remove the static_casts.

**Comment by tlemo** [comment]
Would auto + the notation proposed part of the expression evaluator aleviate some of this pain?
(while also adding a bit of a safety net compared to a static_cast)

Ie. we'd replace:
`TensorView* tv2 = static_cast<TensorView*>(add(tv1, new Float(3.0)));`
with:
`auto tv2 = add(tv1, new Float(3.0))->as<TensorView>();`

https://github.com/csarofeen/pytorch/blob/1b47c923a6c4c57a975c44a5b0a8a9967b1b9a53/torch/csrc/jit/codegen/cuda/ir_base_nodes.h#L98-L108
