### ISSUE TITLE
Consider splitting test_gpu.cpp

### ISSUE THREAD

**Issue by naoyam** [csarofeen/pytorch#388]
Our test source file is getting larger. It currently has more than 6k lines. Maintaining it is becoming cumbersome. Consider splitting it into multiple files.

**Comment by csarofeen** [comment]
We may want to start by integrating `makeSymbolicTensor` and `makeContigTensor` into "real" api calls in the code generator. Then breaking out some utility functions that are common in the tests. Not sure how we want to split the file into more, i.e. what categories would make sense?
