### ISSUE TITLE
Connect up the GELU operation in the parser to the Codegen operation.

### ISSUE THREAD

**Issue by kevinstephano** [csarofeen/pytorch#414]
## 🚀 Feature
Connect the Pytorch IR gelu op `aten::gelu(Tensor self) -> Tensor` to our internal Codegen op for gelu.

https://github.com/csarofeen/pytorch/blob/0722db455c835549d143ef6f31beac157bc9ddd1/torch/csrc/jit/codegen/cuda/type.h#L83

## Motivation

Operation found in Bert

**Comment by jjsjann123** [comment]
Closing as we already have gelu support in parser and I verified that `torch.nn.GELU()` node could be handled. Feel free to open this if we find out gap in support.
