### ISSUE TITLE
kir::IrPrinter improvements

### ISSUE THREAD

**Issue by tlemo** [csarofeen/pytorch#416]
1. Verbose mode. This would add details omitted from the default format.

2. Print TensorView shapes (TensorDomains)
    (dump them as declarations before the kernel body?)

3. Add a `PYTORCH_CUDA_FUSER_DUMP_KIR`, similar to PYTORCH_CUDA_FUSER_DEBUG dumping for Kernel CUDA code.

4. Make sure we can correlate thread dimensions with scalar values.

**Comment by tlemo** [comment]
5. Print all the expression definitions, even if they are not explicitly listed in the expr list?

**Comment by csarofeen** [comment]
Closing this as stale.
