### ISSUE TITLE
Calling NamedScalar::getParallelIndex outside of GPU::lower fails

### ISSUE THREAD

**Issue by rdspring1** [csarofeen/pytorch#450]
## 🐛 Bug

`NamedScalar::getParallelIndex()` uses `IrBuilder` to create `kir::NamedScalar` node.
see https://github.com/csarofeen/pytorch/blob/20_10_20_devel/torch/csrc/jit/codegen/cuda/kernel_ir.cpp#L33-L37

This function is called through `IterDomain::extent()`. 
see https://github.com/csarofeen/pytorch/blob/20_10_20_devel/torch/csrc/jit/codegen/cuda/kernel_ir.cpp#L101

We can look at the extent of a `kir::IterDomain` outside of GpuLower kernel generation.
see https://github.com/csarofeen/pytorch/blob/20_10_20_devel/torch/csrc/jit/codegen/cuda/executor_utils.cpp#L219

In this case, `GpuLower::current()->kernel()` fails, since we are not actively generating a kernel in `GpuLower::lower()`.

**Comment by tlemo** [comment]
In the `bindKernelInputs()` case, we're only looking at Kernel inputs, so we shouldn't have thread extents.

In general, the distinction between "raw extent" and "extent" (ex. the `IterDomain::extent()` magic) is problematic indeed and we should find a better solution.
