### ISSUE TITLE
cache_after sets computeAt of a cache tensor even when the original tensor does not have computeAt.

### ISSUE THREAD

**Issue by naoyam** [csarofeen/pytorch#483]
https://github.com/csarofeen/pytorch/blob/20_10_20_devel/torch/csrc/jit/codegen/cuda/tensor_view.cpp#L588-L598

This path is taken when the original tensor does not have computeAt.

```
 // Check users of this TV for computeAt for cache_after on inputs
    for (auto expr : fusion()->unordered_uses(consumer)) {
      for (TensorView* output :
           ir_utils::filterByType<TensorView>(expr->outputs())) {
        if (output->hasComputeAt()) {
          TransformReplay::replayPasC(consumer, output, -1);
          auto output_ca_pos = output->getThisComputeAtAxis();
          consumer->setComputeAt(output, output_ca_pos);
        }
      }
    }
```

Not sure whether setting computeAt of the cache tensor makes sense in this case. It may be convenient if that's what users would do anyway, but I'm not sure whether that's the case. Also, this code would potentially call setComputeAt with different target tensors, which seems problematic.

**Comment by csarofeen** [comment]
Caching requires no compute at to be set, so closing.
