### ISSUE TITLE
computeAt order

### ISSUE THREAD

**Issue by naoyam** [csarofeen/pytorch#502]
In `scheduleReduction`, computeAt is applied to an rfactor tensor and the original reduction tensor, and then to the reduction tensor and its consumer. For example:

https://github.com/csarofeen/pytorch/blob/de98b4763c5e5c80e6ef4dbf3604bbb11d0dc666/torch/csrc/jit/codegen/cuda/scheduler.cpp#L553-L562

This can lead to invalid tensors since the second computeAt may modify the original reduction tensor, invalidating the computeAt state of the rfactor tensor. For example, here is the fusion of `FusionImplicitBroadcast3` before and after the automatic scheduling:

Before:
```
%kernel_math {
T1[ iS3{80}, rS4{4096}, sbS5{1} ] = reduction( T0[ iS0{80}, iS1{4096}, sbS2{1} ], op = add, initial value = float(0) )
T2[ iS6{80}, rS7{1} ] = reduction( T1[ iS3{80}, rS4{4096}, sbS5{1} ], op = add, initial value = float(0) )
}
```

After:
```
%kernel_math {
T3[ iS23{( ceilDiv(( 80 * 1 ), blockDim.x) )}, iS24{blockDim.x}, iS26{blockDim.y}rf, iS28{gridDim.y}rf, rS29{( ceilDiv(( ceilDiv(( ceilDiv(4096, blockDim.y) ), gridDim.y) ), 4) )}rf, rS30{4}rf ] compute_at( T1, 4 ) = reduction( T0[ iS0{80}, iS1{4096}, sbS2{1} ], op = add, initial value = float(0) )
T1[ iS38{( ceilDiv(80, blockDim.x) )}, iS39{blockDim.x}, sbS32{1}, rS36{blockDim.y}, rS37{gridDim.y} ] compute_at( T2, 3 ) = reduction( T3[ iS23{( ceilDiv(( 80 * 1 ), blockDim.x) )}, iS24{blockDim.x}, iS26{blockDim.y}rf, iS28{gridDim.y}rf, rS29{( ceilDiv(( ceilDiv(( ceilDiv(4096, blockDim.y) ), gridDim.y) ), 4) )}rf, rS30{4}rf ] compute_at( T1, 4 ), op = add, initial value = float(0) )
T2[ iS17{( ceilDiv(80, blockDim.x) )}, iS18{blockDim.x}, rS7{1} ] = reduction( T1[ iS38{( ceilDiv(80, blockDim.x) )}, iS39{blockDim.x}, sbS32{1}, rS36{blockDim.y}, rS37{gridDim.y} ] compute_at( T2, 3 ), op = add, initial value = float(0) )
}
```

`T3` is the rfactor tensor of `T1` and is computed at `T1` of position 4. However, the first 4 axes of the two tensors do not match:

```
T3:  iS23{( ceilDiv(( 80 * 1 ), blockDim.x) )}, iS24{blockDim.x}, iS26{blockDim.y}rf, iS28{gridDim.y}rf
T1:  iS38{( ceilDiv(80, blockDim.x) )}, iS39{blockDim.x}, sbS32{1}, rS36{blockDim.y}
```

It's actually interesting this fusion still goes through the lowering steps without any problem. We should probably do some validation before lowering. 

Changing the order of computeAt seems to fix the problem, i.e., computeAt between the reduction and its output tensors, and then the rfactor and reduction tensors. 

```
%kernel_math {
T3[ iS40{( ceilDiv(80, blockDim.x) )}, iS41{blockDim.x}, sbS21{1}, iS26{blockDim.y}rf, iS28{gridDim.y}rf, rS29{( ceilDiv(( ceilDiv(( ceilDiv(4096, blockDim.y) ), gridDim.y) ), 4) )}rf, rS30{4}rf ] compute_at( T1, 5 ) = reduction( T0[ iS0{80}, iS1{4096}, sbS2{1} ], op = add, initial value = float(0) )
T1[ iS38{( ceilDiv(80, blockDim.x) )}, iS39{blockDim.x}, sbS32{1}, rS36{blockDim.y}, rS37{gridDim.y} ] compute_at( T2, 3 ) = reduction( T3[ iS40{( ceilDiv(80, blockDim.x) )}, iS41{blockDim.x}, sbS21{1}, iS26{blockDim.y}rf, iS28{gridDim.y}rf, rS29{( ceilDiv(( ceilDiv(( ceilDiv(4096, blockDim.y) ), gridDim.y) ), 4) )}rf, rS30{4}rf ] compute_at( T1, 5 ), op = add, initial value = float(0) )
T2[ iS17{( ceilDiv(80, blockDim.x) )}, iS18{blockDim.x}, rS7{1} ] = reduction( T1[ iS38{( ceilDiv(80, blockDim.x) )}, iS39{blockDim.x}, sbS32{1}, rS36{blockDim.y}, rS37{gridDim.y} ] compute_at( T2, 3 ), op = add, initial value = float(0) )
}
```

While this doesn't seem to cause any problem with our current test cases, I found this inconsistency while working on an indexing issue (#382). I have a working fix for it, but I needed to change the order of computeAt as explained above. See #501.

Does this make sense? Looks like all of the separate cases in `scheduleReduction` applies computeAt from an rfactor tensor.

**Comment by jjsjann123** [comment]
> This can lead to invalid tensors since the second computeAt may modify the original reduction tensor, invalidating the computeAt state of the rfactor tensor

I thought in that case our second `computeAt` should propagate to dependents of reduction output, i.e. the rfactored tensor should be updated if second `computeAt` updates its inlined tensor.
My understanding of `computeAt` is that it defines how loops should be nested/shared, but it's not directly generating the loops. I'm not aware that `computeAt` calls should follow the flow of schedule propagation.

But that's mostly talking without knowing much about the implementation, if it contradicts to what we support now, we should take in those changes in #503. 
cc'ing @kevinstephano

**Comment by naoyam** [comment]
> I thought in that case our second `computeAt` should propagate to dependents of reduction output, i.e. the rfactored tensor should be updated if second `computeAt` updates its inlined tensor.

As far as I see, the current computeAt implementation does not do propagation beyond the producer tensor (i.e., producers of the producer). We could probably do that as well if desired.
