### ISSUE TITLE
Allocation of 0-dim tensors

### ISSUE THREAD

**Issue by naoyam** [csarofeen/pytorch#508]
Currently, we throw internal error exceptions when 0-dim tensors need to be allocated:

https://github.com/csarofeen/pytorch/blob/ca21971712e22119f6d2a02583a5742d4a0c5c6e/torch/csrc/jit/codegen/cuda/codegen.cpp#L606

I believe we should do either:

1. Support allocations of 0-dim tensors, or
2. Make it a user error (i.e., `TORCH_CHECK`)

If we decide to make it an error, it would be better if we could do so earlier than the codegen time.

**Comment by tlemo** [comment]
I believe the check is correct: in the Kernel IR we don't overload tensors and scalars, so if we want to allocate a scalar we should generate it as such.

So the fix would be to allow allocation of scalars when needed.

**Comment by naoyam** [comment]
Does that mean 0-dim tensors are not allowed in the Kernel IR?

**Comment by tlemo** [comment]
> Does that mean 0-dim tensors are not allowed in the Kernel IR?

Correct. An explicit goal for Kernel IR is to have a single way to represent something, in this case scalars and tensors.

**Comment by naoyam** [comment]
OK. Currently, in the Fusion IR level, 0-dim tensors are allowed, so when we lower them, do we need to convert them to scalar nodes?

**Comment by tlemo** [comment]
Yes, the "scalar" tensors in Fusion IR need to be lowered as real scalars. I think I already made changes to make sure this happens but I may have missed some cases.

**Comment by csarofeen** [comment]
This should be revisited. CC @jjsjann123 @shmsong
