### ISSUE TITLE
Printing Fusion IR nodes just show object addresses

### ISSUE THREAD

**Issue by naoyam** [csarofeen/pytorch#514]
When Fusion IR node pointers are printed to `std::ostream`, sometimes only their addresses are printed.

Reproducer:
https://github.com/csarofeen/pytorch/blob/c10-str-test/test/cpp/jit/test_gpu.cpp#L7090-L7097

Changed `TensorView::TensorView` as:
https://github.com/csarofeen/pytorch/blob/c10-str-test/torch/csrc/jit/codegen/cuda/tensor_view.cpp#L29-L30

The result was:
```
[ RUN      ] NVFuserTest.Stringify
In ctor: 0x563e772dedb0
In ctor (const*): T0[ iS0{i1} ]
c10::str(TensorView*): T0[ iS0{i1} ]
c10::str(const TensorView*): T0[ iS0{i1} ]
```

In the Kernel IR, this is avoided by using `kir::toString`.

**Comment by csarofeen** [comment]
Statements have a `toString` and `toInlineString` method which should prevent this behavior.
