### ISSUE TITLE
Collapse multiple grid reductions into one when possible (Validating grid reduction usage)

### ISSUE THREAD

**Issue by naoyam** [csarofeen/pytorch#542]
## 🚀 Feature

Grid reductions have several constraints unless we rely on cooperative threading. We try to enforce correctness in the presence of grid reductions by setting up necessary predicates, but we should also avoid reduction patterns that are overly complex.

For example, if a tensor is first reduced over a grid and then a thread block, it should be done by just one gridReduce. 

When the second reduction is done serially, it means the first grid reduction must be located in a loop, which isn't supported.

**Comment by csarofeen** [comment]
This should be revisited. We do have support now for cooperative group launches, but the point here still remains that multiple reductions that are parallelized should be collapsed into one.

**Comment by naoyam** [comment]
Closing as we support grouped grid reductions
