### ISSUE TITLE
Consider expressing swizzle as an expression on IterDomain

### ISSUE THREAD

**Issue by naoyam** [csarofeen/pytorch#581]
Swizzle is currently implemented as an extra step in the index generation (`generateIndexAndExtentMap`). While it does its job, it may be more robust and simpler to represent swizzling as a new expression on IterDomains. Like `Merge` and `Split`, `Swizzle` would have input and output IterDomains. The outputs would be marked as swizzled, and `IndexCompute` would use that information to generate swizzled index expressions.

**Comment by csarofeen** [comment]
This is the direction Shiming is going in, CCing him.
