### ISSUE TITLE
Ensure producer-consumer relationship when forwarding mismatched merge

### ISSUE THREAD

**Issue by naoyam** [csarofeen/pytorch#621]
`BestEffortReplay::BestEffortReplay()` with forwarding enabled may not be safe when the two domain parameters are not in a producer-consumer relationship. 

See e700069c151d9beeb162bd1d1b4ecc8c355ab66e

**Comment by csarofeen** [comment]
We have `BestEffortReplay` `replay(PasC,CasP)` variants and ones that require an ID map. This isn't exclusively safe, but I believe the interface makes this clear now. Please reopen if you disagree.
