### ISSUE TITLE
Exposing internal behavior to users

### ISSUE THREAD

**Issue by naoyam** [csarofeen/pytorch#638]
Our system is becoming a lot more interesting with powerful capabilities such as automated scheduling, kernel segmentation, etc., which are of course very exciting, but they are also making our system more obscure and difficult for the user to see what the system does for the user input program and why. 

A good optimizing compiler usually has a verbosity option to print messages when certain optimizations can be applied or why can't be applied otherwise. Our system should also expose internal algorithm decisions when the user instructs to do so. For example, information like why a given fusion can't be compiled to a single kernel would be valuable feedback to the user.

**Comment by csarofeen** [comment]
CC-ing @jjsjann123 and @kevinstephano is there any immediate actions we want to take here beyond the current debug functionality we have?

**Comment by kevinstephano** [comment]
This sounds similar in what Jie is trying to do in adding debug info to the fuse/not-fuse decisions.

**Comment by jjsjann123** [comment]
> information like why a given fusion can't be compiled to a single kernel would be valuable feedback to the user.

Good point!
I have a short subgraph explaining some of our codegen dump knob from environment variable, even tho i didn't include segmentation in that one. https://github.com/csarofeen/pytorch/pull/1328/files#diff-be7755dee6919a40d24d3c3d0948006330e88cf22d2bbda01395b9f92d7ce2e3R209-R215

Do you that's a good direction to go, documentation on existing knobs? IMO, it strikes a balance of what's readily available and not going too deep into our code base.

**Comment by naoyam** [comment]
Thanks @jjsjann123 . I added a comment at the PR. I close this issue as it's being addressed there.
