### ISSUE TITLE
Use user facing lookup map instead of exposing IrCloner in Fusion::copy

### ISSUE THREAD

**Issue by shmsong** [csarofeen/pytorch#643]
Need to introduce a node name based lookup feature to get IR node pointers from names on a `Fusion` object. 

## Motivation

The need for this feature concerns [Automatic Kernel Segmentation](https://github.com/csarofeen/pytorch/pull/589), or more generally any analysis/optimization that need to be done on multiple fusion objects, e.g. copying nodes etc. 

As a motivating example, current implementation of `Fusion::Copy` has to use the whole `IrCloner` to provide a mapping between a fusion and its copy. This exposes internal details and the API can also be improved. 

```cpp
static IrCloner copy(const Fusion* from, Fusion* to);
```

A [discussed](https://github.com/csarofeen/pytorch/pull/555#discussion_r539676187) improvement would use a public name based lookup and couple the IR nodes between the `Fusion`s using names. 

```cpp
  // Example: tv3, tv1 from fusion1
  fusion0.removeOutput(fusion0.lookupNode(tv3->name()));
  fusion0.addOutput(fusion0.lookupNode(tv1->name()));
```

**Comment by tlemo** [comment]
To summarize the key concerns (see also #555 for the original conversation)

1. The cloning machinery (IrCloner) is intended to be an internal detail, limited to the implementation of Fusion copy operations. Using clone() to extract the mapping is misleading (no cloning actually happens) and depends on knowledge of how cloning works (creating a hidden tight coupling)

2. Having both a Fusion::copy() in the addition to the usual copy/move operations is a poor interface

3. Attempting to limit the scope of Fusion::copy() by either making it protected and/or friending the users is not a solution 
- protected is the same as public from an [open-closed][1] design perspective
- adding friends exposes all the Fusion internals, in effect making things worse compared to having copy() public

[1]: https://en.wikipedia.org/wiki/Open%E2%80%93closed_principle

**Comment by csarofeen** [comment]
I disagree name look ups is better than exposing the details of how something is copied. Closing as will not fix.
