### ISSUE TITLE
Parallelization on InterDomains used in input Vals should be no-op

### ISSUE THREAD

**Issue by naoyam** [csarofeen/pytorch#654]
Parallelizing input vals doesn't make sense, so it should be no-op. While it seems harmless, it could indirectly result in a failure if done. Here's an example that fails at a lowering step.

```
TEST(NVFuserTest, FusionParallelizeInputIterDomain_CUDA) {
  Fusion fusion;
  FusionGuard fg(&fusion);

  auto tv0 = makeSymbolicTensor(1);
  fusion.addInput(tv0);

  auto tv1 = add(tv0, new Double(1));
  fusion.addOutput(tv1);

  tv1->split(0, 4);

  tv1->axis(-1)->parallelize(ParallelType::TIDx);
  tv0->axis(-1)->parallelize(ParallelType::TIDx); // Shouldn't be done

  fusion.printMath();
  fusion.printKernel();
}
```

```
unknown file: Failure
C++ exception with description "Splitting an axis of non-Serial iteration is not supported at this time. Parallelization strategy must be set after calling split.
Exception raised from split at ../torch/csrc/jit/codegen/cuda/ir_nodes.cpp:515 (most recent call first):
frame #0: <unknown function> + 0xdcab6 (0x7fee57df1ab6 in /home/nmaruyama/pytorch/debug1/build/lib/libc10.so)
```

This isn't very helpful for a user as there is no explicit splitting of parallelized axes. I believe this is a side effect of not doing computeAt transformations for input tensors but marking its IterDomain parallelized.

**Comment by csarofeen** [comment]
This failure doesn't happen anymore and kernel is generated fine. Do we care if it shows up as parallelized even though it has no impact?

**Comment by naoyam** [comment]
I think at some point we decided not to care if an IterDomain is parallelized or not when it's split. That is still checked at `TensorView::split`, but not in `IterDomain::split`. 

I don't think there's any other side effect, although I still think it doesn't makes much sense as it doesn't seem natural to have parallelization of inputs.

**Comment by naoyam** [comment]
Closing as there's no actual problem
