### ISSUE TITLE
Generic support for passing pure scalar expressions between segmented groups

### ISSUE THREAD

**Issue by shmsong** [csarofeen/pytorch#660]
This is a tracker issue on the implementation of scalar support for segmented fusions. 

Without supporting any scalar outputs from kernels we might want to consider using expression evaluators on the segmented runtime to fill in the scalar intermediates.

**Comment by jjsjann123** [comment]
I'm running into new issues after fix #661 .
I'm getting codegen result as (note the argument `T11.size[2]`):
```
__global__ void kernel3(Tensor<float, 3> T3, Tensor<float, 4> T2, Tensor<float, 4> T11, Tensor<float, 4> T9, int64_t T11.size[2], int64_t T11.size[3], int64_t T11.size[1], Tensor<float, 4> T24, Tensor<float, 3> T12, Tensor<float, 4> T13, Tensor<float, 4> T14, Tensor<float, 4> T17, Tensor<float, 1> T15, Tensor<float, 4> T21, Tensor<float, 4> T23, Tensor<float, 1> T19, Tensor<float, 4> T20) {
  alignas(4) extern __shared__ char array[];
  void* shared_mem = array;
  double d54;
  d54 = 1 * T11.size[3];
  double d55;
  d55 = d54 * T11.size[2];
  double d56;
  d56 = d55 * T11.size[1];
```

Added another repro in the original PR #658, you can try the commit 2a13012.

It's taking argument as `T11.size[2]`

**Comment by csarofeen** [comment]
@jjsjann123 @shmsong is this still an issue?

**Comment by shmsong** [comment]
Shouldn't be issue anymore as currently segmenter merges all producer scalar exps in each kernel. Could re-open if needed.
