### ISSUE TITLE
exprs(true) called on freshly created fusion segfaults.

### ISSUE THREAD

**Issue by jjsjann123** [csarofeen/pytorch#68]
## 🐛 Bug

This segfaults.
```
  Fusion fusion_test;                                                                                                                                                                                                
  fusion_test.exprs(true);                                                                                              
```

I run into this when I was calling `hasReduction` as I progressively parse the graph.

**Comment by csarofeen** [comment]
Fixed in https://github.com/csarofeen/pytorch/pull/77 with https://github.com/csarofeen/pytorch/blob/3ecb427fe8736de61ca285bffc3f05634b4c62b9/torch/csrc/jit/codegen/cuda/iter_visitor.cpp#L59-L60

**Comment by jjsjann123** [comment]
No more segfault in cf307bd146b9a879e4e683c265ff4a62866d0329. closing.
