### ISSUE TITLE
[in-place BN fw/bw] certain schedule changes behavior or trivial reduction

### ISSUE THREAD

**Issue by jjsjann123** [csarofeen/pytorch#716]
## 🐛 Bug

Our inplace update hack relies on a straightforward update on output tensor in order to work:
e.g. In the example below, if we want to increment input `T0`, we are creating an output tensor `T1` and alias it to `T0`. Look at the example below vvv.
```
__global__ void kernel1(Tensor<float, 1> T0, Tensor<float, 1> T3) {
  float T1[1];
  T1[0]
     = T0[(threadIdx.x * T0.stride[0])];
  float T2[1];
  T2[0]
    = T1[0]
    + (float) 1;
  T3[(threadIdx.x * T3.stride[0])]
     = T2[0];
}
```

However, in cases when we have complicated scheduling, we somehow arrived at a spot where the output tensor could become a trivially reduced tensor and codegen spits out initialization and later accumulates on it. This unfortunately breaks the aliasing.
```
__global__ void kernel1(Tensor<float, 1> T0, Tensor<float, 1> T3) {
  T3[(blockIdx.x * T3.stride[0])] = 0;                # initialize T3 to 0 would also set T0 to be 0
  float T1[1];
  T1[0]
     = T0[(blockIdx.x * T0.stride[0])];
  float T2[1];
  T2[0]
    = T1[0]
    + (float) 1;
  for(size_t ki26 = 0; ki26 < (ceilDiv(1, 1)); ++ki26) {
    for(size_t ki27 = 0; ki27 < 1; ++ki27) {
      T3[(blockIdx.x * T3.stride[0])]                  # accumulation is also dangerous
        = T3[(blockIdx.x * T3.stride[0])]
        + T2[0];
    }
  } 
}
```

The code was generated with

```
TEST(NVFuserTest, FusionIOTensorTrivialReductionRepro_CUDA) {
  Fusion fusion;
  FusionGuard fg(&fusion);
 
  constexpr int M = 10;
  constexpr int N = 11;
 
  auto tv0 = makeSymbolicTensor(1);
  fusion.addInput(tv0);
 
  std::vector<int> reduction_axes = {1};
  std::vector<bool> broadcast_mask = {false, true};
 
  auto tv0_bcast = broadcast(tv0, broadcast_mask);
  auto path1_bcast = add(tv0_bcast, new Double(1.0));
  auto path1 = sum(path1_bcast, reduction_axes);
  fusion.addOutput(path1);
 
#if true // set this to false to see the right result
  auto p = path1->split(1, 1);
  path1->axis(0)->parallelize(ParallelType::BIDx);
  path1->rFactor({1});
  tv0->computeAt(path1, 1);
#else
  path1->axis(0)->parallelize(ParallelType::TIDx);
  path1->axis(1)->parallelize(ParallelType::BIDx);
  tv0->computeAt(path1, 1);
#endif
 
  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  at::manual_seed(0);
  at::Tensor t0 = at::randn({M}, options);
  at::Tensor t0_ref = t0.clone();
  std::vector<IValue> aten_inputs = {t0};
 
  FusionExecutor fe;
  fe.compileFusion(&fusion);
  // inplace op, we are adding t0 to itself
  auto outputs = fe.runFusion(aten_inputs, {t0});
 
  TORCH_CHECK(outputs[0].allclose(t0_ref.add(1)));
}

```

## To Reproduce

Repro created here: https://github.com/csarofeen/pytorch/tree/trivial_reduction_repro
You can run with
`PYTORCH_NVFUSER_DUMP=cuda_kernel ./build/bin/test_jit --gtest_filter="*FusionIOTensorTrivialReductionRepro*"`

## Additional context

This should have really be a feature request instead of a bug report.
I don't know how hard it is for codegen/lowering to identify the trivial reduction buried under transformations.

**Comment by shmsong** [comment]
So the split `IterDomain` becomes something like `IS19{( ceilDiv(1, 1) )}`, which cannot be found to be a 1 by `isOneInt()`. Generally a contant folder would help but I guess we could also just specialize size 1 for `split` and `merge`?

**Comment by naoyam** [comment]
There could be operations like `split(1, 4)`, which would generate an axis with extent 4. Still, if an axis is originally trivial reduction, splitting it with any factor should still result in trivial reductions. 

I think we should look at root domains. If a root domain has only trivial reductions, it should be safe to replace it with a unary set. See #726. There is also another issue. See #727 as well.

**Comment by naoyam** [comment]
The reproducer seems working fine with #726. It is added as a test in the PR branch.

**Comment by jjsjann123** [comment]
Looks like the repro did pass, I'm closing this one.
