### ISSUE TITLE
Revisit graph specialization approach used for mixing eager-mode/scripting autocast

### ISSUE THREAD

**Issue by tlemo** [csarofeen/pytorch#720]
#711 added basic support for mixing eager mode and scripted autocast. Although straightforward, that approach pushes the vendor-specific autocast logic into the core of `GraphFunction`. Another approach, which may fit better into the profiling executor design is to use a custom node similar to `prim::RequiresGradCheck` and wrap the specialized graph version into IR 'if' branches.

One important consideration if we decide to go that direction is to make sure we don't specialize the paths we don't need since the specialization instantiation is potentially expensive.

See https://dev-discuss.pytorch.org/t/executionplan-caching-in-profilinggraphexecutorimpl/163 for a discussion thread on this.

**Comment by csarofeen** [comment]
Closing as will not fix as autocasting for TorchScript is as good as we're intending to get it.
