### ISSUE TITLE
Revisit `CastPolicy::promote` implementation

### ISSUE THREAD

**Issue by tlemo** [csarofeen/pytorch#721]
The current `CastPolicy::promote` implementation is pessimistically default to `float32` if any of the dtypes are not known - which is the case in most initial IR graphs.

A better solution would be to use a custom operation to accurately promote to the widest dtype, see https://dev-discuss.pytorch.org/t/prim-autocast-promote-operation/158/4 for details.

**Comment by csarofeen** [comment]
Closing as will not fix as autocasting for TorchScript is as good as we're intending to get it.
