### ISSUE TITLE
Problems with trivial reductions

### ISSUE THREAD

**Issue by naoyam** [csarofeen/pytorch#727]
There are two issues with trivial reductions:

1. Trivial reductions are supposed to be lowered to unary set. However, it fails when a reduction axis is split. See https://github.com/csarofeen/pytorch/issues/716#issuecomment-792380664.
2. Trivial reductions do not need actual loops, but the current codegen emits anyway. 

PR #726 should address the first issue.

For the second issue, it is not harmful unless computeAt is done involving such trivial reductions. Loops with extent 1 would be generated, but that's just fine at least functionally. However, in #724, ComputeAtRootMap is relaxed to allow certain mappings based on the assumption that trivial reductions do not result in actual loops, which is not really the case. For example, this test fails at the result validation:

```
TEST(NVFuserTest, FusionRootMappingTrivialReduction_CUDA) {
  Fusion fusion;
  FusionGuard fg(&fusion);

  auto tv0 = makeSymbolicTensor(1);
  auto tv1 = makeSymbolicTensor(2);

  fusion.addInput(tv0);
  fusion.addInput(tv1);

  auto tv2 = broadcast(tv0, {true, false});
  auto tv3 = sum(tv2, {0});
  auto tv4 = add(tv2, tv1);

  fusion.addOutput(tv3);
  fusion.addOutput(tv4);

  ComputeAtRootDomainMap map;
  map.build();

  checkIdMapped(
      map, tv2, tv2->getRootDomain()[0], tv4, tv4->getRootDomain()[0], true);
  checkIdMapped(
      map, tv2, tv2->getRootDomain()[0], tv3, tv3->getRootDomain()[0], true);

  tv2->computeAt(tv4, -1);

  fusion.printKernel();

  const int x = 11;
  const int y = 12;
  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  at::Tensor t0 = at::randn({x}, options);
  at::Tensor t1 = at::randn({y, x}, options);
  std::vector<IValue> aten_inputs = {t0, t1};

  FusionExecutor fe;
  fe.compileFusion(&fusion);
  auto outputs = fe.runFusion(aten_inputs);

  auto t3 = t0;
  auto t4 = t0.unsqueeze(0).expand({y, x}) + t1;

  testValidate(&fusion, outputs, aten_inputs, {t3, t4}, __LINE__, __FILE__);
}
```

The generated kernel:

```
__global__ void CUDAGeneratedKernel(Tensor<float, 1> T0, Tensor<float, 2> T1, Tensor<float, 1> T3, Tensor<float, 2> T4) {
  for(size_t ki26 = 0; ki26 < 1; ++ki26) {
    for(size_t ki27 = 0; ki27 < T0.size[0]; ++ki27) {
      float T2[1];
      T2[0]
         = T0[(ki27 * T0.stride[0])];
      T3[ki27]
         = T2[0];
      T4[(ki26 * T4.stride[0]) + ki27]
        = T2[0]
        + T1[(ki26 * T1.stride[0]) + (ki27 * T1.stride[1])];
    }
  }
}
```

Notice that the outer-most loop has extent one, which is derived from `tv3->axis(0)`. That's fine for `T3` but not for `T4` since `T4`'s first axis has actually an extent of `T1.size[0]`.

The problem is that `tv2->axis(0)` is determined to be mappable with both `tv3->axis(0)` and `tv4->axis(0)`. This is semantically correct, assuming there is no loop generated for `tv3->axis(0)`, which is in fact not the case. As shown above, the outer-most loop is the one corresponding to `tv3->axis(0)`. 

I think that just using a unary set for a given trivial reduction isn't sufficient. If we replace the trivial reduction axis, `tv3->axis(0)`, with a broadcast axis, then we would not generate the extent-one loop since ComputeAtMap would not pick it as the concrete IterDomain, which would then correctly generate the outer-most loop with the `T1.size[0]`. 

I'm still not 100% clear whether there could be any negative side effect.

**Comment by csarofeen** [comment]
What if we more actively tracked a trivial reduction? We could simply check reduction extent isOneInt in the compute at map and not prefer it as if it was broadcast.

The other thing that may be required here is to actually simplify ceilDiv and mul in our IR so if any of the arguments are 1 then we don't generate something like ceilDiv(1, 1) and 1*1 which could throw off detection.

The other option would be to track trivial reduction axes like we do with broadcasted With/Without Stride axes.
