### ISSUE TITLE
Allow users to specify output contiguity.

### ISSUE THREAD

**Issue by csarofeen** [csarofeen/pytorch#743]
The test `PersistentNormLocalShared` breaks due to https://github.com/csarofeen/pytorch/pull/741 because it expects a noncontiguous output. Previously we were always using stride information even if marked contiguous which we've changed. We also assume output tensors are contiguous because we assume we will allocate them during practical applications. We should have some mechanism to specify an output is noncontiguous, as well as potentially other buffers.

**Comment by naoyam** [comment]
This is also helpful for the HPC users. I'll look into it.
