### ISSUE TITLE
blockBroadcast is used for input tensor

### ISSUE THREAD

**Issue by naoyam** [csarofeen/pytorch#772]
`blockBroadcast` should be only used when it is actually necessary. Specifically, we track whether only certain threads like `threadIdx.x == 0` have valid values, and those tensors should be the only ones that we pick `blockBroadcast`. The current logic is in `getParallelBroadcastDomains`.

@csarofeen reported it's used for input tensors. All threads should have valid values of input tensors, so if `blockBroadcast` is used, that should be a bug.

@csarofeen Can you please share a reproducer?

**Comment by csarofeen** [comment]
I don't seem to be able to do this, conflated it with something else. Closing for now unless I do find an instance where this happens.
