### ISSUE TITLE
Stream capture failure when the caching allocator is disabled

### ISSUE THREAD

**Issue by naoyam** [csarofeen/pytorch#810]
With the latest develop branch, when `PYTORCH_NO_CUDA_MEMORY_CACHING` is defined, the Python tests fail as follows:

```
(pytorch-debug2) naoya-srv:debug2$ export PYTORCH_NO_CUDA_MEMORY_CACHING=1                                                                                                                                                 
(pytorch-debug2) naoya-srv:debug2$  python test/test_jit_cuda_fuser.py                                                              
/home/nmaruyama/pytorch/debug2/torch/backends/cudnn/__init__.py:73: UserWarning: PyTorch was compiled without cuDNN/MIOpen support. To use cuDNN/MIOpen, rebuild PyTorch making sure the library is visible to the build system.
  warnings.warn(
/home/nmaruyama/pytorch/debug2/torch/testing/_internal/common_utils.py:128: UserWarning: fast math disabled in nvfuser, try set `PYTORCH_NVFUSER_DISABLE_FASTMATH=0` (Triggered internally at  ../torch/csrc/jit/codegen/cuda/executor_utils.cpp:543.)
  return callable(*args, **kwargs)
.............ss....../home/nmaruyama/pytorch/debug2/torch/testing/_internal/common_utils.py:128: UserWarning: FALLBACK path has been taken. This is an indication that codegenFailed for some reason. To debug try disable codegen fallback pathvia setting the env variable`export PYTORCH_NVFUSER_DISABLE_FALLBACK=1` (Triggered internally at  ../torch/csrc/jit/codegen/cuda/manager.cpp:305.)
  return callable(*args, **kwargs)
..........Eterminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: operation not permitted when stream is capturing
Exception raised from uncached_delete at ../c10/cuda/CUDACachingAllocator.cpp:1179 (most recent call first):
```

The exception happens during `uncached_delete`, so this is likely to happen only when the caching allocator is disabled. I'm using a debug build, but I'm not sure if that matters.

**Comment by jjsjann123** [comment]
hmmm, I can't get a repro on my machine even with debug build. I did realize that the system I tried it on is a little out-dated (cuda TK 10.2 + driver 440.33)

What's you CUDA TK version & driver? I'll try that on a newer setup.

**Comment by naoyam** [comment]
It's 11.2 with 460.27. 

This error seems to happen during stream capture for CUDA Graphs. Doesn't 10.2 support CUDA Graphs? Also, we recently disabled some test using CUDA Graphs on CUDA 10, so if you're using CUDA 10, it may not be actually executed.

**Comment by jjsjann123** [comment]
Thanks for the pointer, now I see it repro'ed at ToT dev branch. I'll bisect it tomorrow.

**Comment by naoyam** [comment]
The error happens at https://github.com/csarofeen/pytorch/blob/20_12_3_devel/test/test_jit_cuda_fuser.py#L2092.

```
g.capture_begin()
graph_out = t_jit(graph_in)
g.capture_end()
```

`cudaFree` is called in `t_jit(graph_in)` when caching is not used. I doubt `cudaFree` is capture-safe as it's not associated with a stream.

**Comment by jjsjann123** [comment]
Never mind I did get a repro on release build. Yeah I think it's supposed to fail and everything makes sense again.

I'll disable the test when caching allocator is disabled.

**Comment by naoyam** [comment]
Is it guaranteed that memory deallocation never occurs if caching is enabled? I don't know how the allocator is implemented, but wouldn't it automatically do things like compaction automatically when needed? Maybe this is highly unlikely to happen, though.

**Comment by jjsjann123** [comment]
> Is it guaranteed that memory deallocation never occurs if caching is enabled? I don't know how the allocator is implemented, but wouldn't it automatically do things like compaction automatically when needed?
in the vanilla caching allocator, it deallocates unused blocks when allocation fails but that's about it that I know.
I know we recently allows memory mapping, so it's possible to do remapping without deallocation, but I don't know/think it's integrated yet.

With Carilli's recent PR to allow private memory pool, I think it doesn't deallocate within the capture session any more.
If you are interested: https://github.com/pytorch/pytorch/pull/51436/

**Comment by naoyam** [comment]
Thanks, good to know it's already taken care of.
