### ISSUE TITLE
Inputs to std::set_union() must be sorted

### ISSUE THREAD

**Issue by tlemo** [csarofeen/pytorch#85]
https://github.com/csarofeen/pytorch/blob/b330974617946c78d0984374edcc7027f35df450/torch/csrc/jit/codegen/cuda/fusion.cpp#L194-L199

The ranges used as inputs to std::set_unions() must be sorted:
https://en.cppreference.com/w/cpp/algorithm/set_union

**Comment by csarofeen** [comment]
Can we just convert all_inputs and outs_inputs to a set instead of unordered_set?
