### ISSUE TITLE
Python test failure (remainder?)

### ISSUE THREAD

**Issue by naoyam** [csarofeen/pytorch#864]
With the latest develop branch, I see this failure:

```
======================================================================
FAIL: test_binary_ops (__main__.TestCudaFuser)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nmaruyama/pytorch/debug1/torch/testing/_internal/common_utils.py", line 1030, in wrapper
    method(*args, **kwargs)
  File "test/test_jit_cuda_fuser.py", line 678, in test_binary_ops
    self._binary_test_helper(op, dtype)
  File "test/test_jit_cuda_fuser.py", line 638, in _binary_test_helper
    self.assertEqual(o, jit_o)
  File "/home/nmaruyama/pytorch/debug1/torch/testing/_internal/common_utils.py", line 1352, in assertEqual
    super().assertTrue(result, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
AssertionError: False is not true : Tensors failed to compare as equal!Found 490 different element(s) (out of 4096), with the greatest difference of 4294967296 (4294967295 vs. -1) occuring at index (0, 0, 2).
```

It looks like the failure happens at the `remainder` op with int64. Here's the last kernel printed when `PYTORCH_NVUFSER_DUMP=cuda_kernel` is set:

```
======= Codegen output for kernel: kernel22 =======

__global__ void kernel22(Tensor<int64_t, 3> T0, Tensor<int64_t, 3> T1, Tensor<int64_t, 1> T2, Tensor<int64_t, 3> T5) {
  if ((((((((blockIdx.x * 1) + (1 - 1)) * 1) + (1 - 1)) * 128) + threadIdx.x) < ((T1.size[0] * T1.size[1]) * T1.size[2]))) {
    constexpr int64_t ki169 = 0;
    constexpr int64_t ki171 = 0;
    int64_t T3[1];
    T3[0]
       = T2[0];
    int64_t T4[1];
    T4[0]
      = T1[(((((((blockIdx.x * 1) + ki169) * 1) + ki171) * 128) + threadIdx.x) * 1)]
      + T3[0];
    T5[(((((((blockIdx.x * 1) + ki169) * 1) + ki171) * 128) + threadIdx.x) * 1)] = remainder(
      T4[0],
      T0[(((((((blockIdx.x * 1) + ki169) * 1) + ki171) * 128) + threadIdx.x) * 1)]);
  }
}

======================================
```

From the error output (`difference of 4294967296 (4294967295 vs. -1)`), it seems to have something to do with integer overflowing. Could this be caused by unsigned 64-bit int vs signed 64-bit int difference?

**Comment by jjsjann123** [comment]
Funny enough this seems to be introduced/exposed by commit, which merely add a `-G` to nvrtc: 1163cf41550eb8d0254475240d30a424a2c443ba

I'll keep digging.

**Comment by naoyam** [comment]
Hmm, that's interesting. I see that some of the recent failures with register usage are caused by the debug option. Changing `-G` to `-lineinfo` seems to avoid the register error. We should have a better control of register pressure, but for the mean time, switching to `-lineinfo` seems fine. That said, no idea why it could affect this test.

**Comment by jjsjann123** [comment]
> We should have a better control of register pressure

Totally agree on this one. I'll put a cap on register usage for nvrtc. Ideally thing should be worked in scheduling heuristics for the best performance, but at least having it at nvrtc level could ensure a successful kernel execution 🤞

**Comment by jjsjann123** [comment]
FYI, I verified that the issue comes from compiler behavior. remainder (%) on zero in int64_t gives different result (sometimes -1 and sometimes uint32_t(-1), depends on the optimization level).
Given that mod by 0 integer is UB, I don't think we get to file a bug here. 🤷 

I have at least forwards it in fb-nvidia slack per Christian's comment.
