### ISSUE TITLE
[computeAt] Assert failure on legit `computeAt`

### ISSUE THREAD

**Issue by jjsjann123** [csarofeen/pytorch#90]
## 🐛 Bug

transform replay is giving me error:
```
unknown file: Failure
C++ exception with description "it != replay_CasP.getReplay().end() INTERNAL ASSERT FAILED at "../torch/csrc/jit/codegen/cuda/transform_replay.cpp":471, please report a bug to PyTorch. Could not find axis, iS{128}rf, requested in replay.
Exception raised from replayCasP at ../torch/csrc/jit/codegen/cuda/transform_replay.cpp:471
```

Repro cpp test:

```
void testGPU_FusionReductionComputeAtRepro() {
  torch::jit::fuser::cuda::CudaKernel prog;
  Fusion& fusion = *prog.fusion_;
  FusionGuard fg(&fusion);

  // Set up your input tensor views
  TensorView* tv0 = makeDummyTensor(2);
  fusion.addInput(tv0);

  TensorView* tv1 = reductionOp(BinaryOpType::Add, {1}, new Float(0), tv0);
  fusion.addOutput(tv1);

  TORCH_CHECK(fusion.hasReduction(), "Could not detect reduction in fusion.");
  tv1->split(1, 128);
  auto tv2 = tv1->rFactor({1});

  tv0->computeAt(tv1, 2); // this is giving me error!

  tv0->axis(0)->parallelize(ParallelType::BIDx);
  tv1->axis(0)->parallelize(ParallelType::BIDx);
  tv2->axis(0)->parallelize(ParallelType::BIDx);
  tv0->axis(-1)->parallelize(ParallelType::TIDx);
  tv1->axis(-1)->parallelize(ParallelType::TIDx);
  tv2->axis(-1)->parallelize(ParallelType::TIDx);

  GPULower gpulw(&fusion);
  std::stringstream cdg;
  gpulw.printKernel(cdg);
  std::cout << cdg.str() << std::endl;
}
```

**Comment by jjsjann123** [comment]
This is not blocking me. I'm reporting the issue here just for record keeping, so later we can verify things are working properly

**Comment by csarofeen** [comment]
Not reproing on 20_6_11_devel now getting 
```
C++ exception with description "Reductions can only be parallelized across dimensions of compile-time known constants.
Exception raised from parallelize at ../torch/csrc/jit/codegen/cuda/ir_internal_nodes.h:294 (most recent call first):
```
which is tracked on https://github.com/csarofeen/pytorch/issues/94

**Comment by jjsjann123** [comment]
Very strange as this still repros for me on b9af528aa06fdd7faea679700709197ebf194fc2 (Which is currently the ToT on `csarofeen/20_6_11_devel`. My previous test was also only 1 commit behind.

And I tried a fresh build and nuked my local pytorch installation as well. :confused: 

This is an assert in our codegen, I don't think it should be related to any of the environment setting.

**Comment by jjsjann123** [comment]
closing per 

> Not reproing on 20_6_11_devel now getting
> 
> ```
> C++ exception with description "Reductions can only be parallelized across dimensions of compile-time known constants.
> Exception raised from parallelize at ../torch/csrc/jit/codegen/cuda/ir_internal_nodes.h:294 (most recent call first):
> ```
> 
> which is tracked on #94
